<a href="https://colab.research.google.com/github/M007AX/FMEPID2026/blob/main/Final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Libraries import

In [1]:
!pip install optuna

Collecting optuna
  Downloading optuna-4.9.0-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (1.18.4)
Collecting colorlog (from optuna)
  Downloading colorlog-6.10.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (26.2)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.50)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (1.3.12)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.5.1)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna) (3.0.3)
Downloading optuna-4.9.0-py3-none-any.whl (425 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 425.6/425.6 kB 14.0 MB/s eta 0:00:00
Downloading colorlog-6.10.1-py3-none-any.whl (11 kB)
Installing collected packages: colorlog, optuna
Successfully installed colorlog-6.10.1 optuna-4.9.0

In [2]:
from sentence_transformers import SentenceTransformer

In [3]:
import xgboost as xgb
import optuna
import pandas as pd
import numpy as np
import joblib
import json
import os

In [4]:
from sklearn.metrics import mean_absolute_percentage_error, r2_score
from sklearn.preprocessing import StandardScaler

In [5]:
import matplotlib.pyplot as plt
import seaborn as sns
import shap

In [6]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.nn import TransformerEncoder, TransformerEncoderLayer
from torch.optim.lr_scheduler import ExponentialLR

In [7]:
np.random.seed(42)
torch.manual_seed(42)

print("All libraries imported successfully.")

All libraries imported successfully.

In [8]:
print(torch.cuda.is_available())

True

# Data

In [9]:
# URL of the raw CSV file on GitHub
url = 'https://github.com/M007AX/FMEPID2026/blob/main/merged_full_df_cleaned.csv?raw=true'
df_full = pd.read_csv(url)

print("Data loaded successfully.")
print(f"Dataset shape: {df_full.shape}")
print("First 10 rows:")
df_full.head(10)

Data loaded successfully.
Dataset shape: (15404, 20)
First 10 rows:

,FIPS,year,median_household_income,poverty_rate,bachelor_plus_rate,unemployment_rate_acs,CO,NO2,PM2_5,PM10,O3,prcCancer_non_skin,prcAsthma,prcCoronaryHeartDisease,prcCOPD,prcSmoking,prcDiabetes,prcLPA,prcObesity,prcStroke
0,1001,2019,58731.0,0.151852,0.265716,0.036766,0.279473,8.327400,8.166278,15.729776,0.029345,7.4,9.7,7.0,8.4,19.3,12.7,32.8,35.6,3.9
1,1001,2020,57982.0,0.152118,0.283175,0.029073,0.266630,7.381128,7.716879,15.417430,0.026228,7.4,10.2,7.9,8.6,19.4,12.9,27.2,35.8,3.8
2,1001,2021,62660.0,0.135785,0.281315,0.028246,0.280704,7.619302,8.185459,15.598320,0.026761,7.2,10.1,6.7,7.6,16.8,12.3,30.0,39.3,3.4
3,1001,2022,68315.0,0.113740,0.295586,0.027685,0.244862,7.416966,7.811314,15.316584,0.028822,6.8,9.8,7.3,8.3,18.0,12.1,27.2,37.6,3.5
4,1001,2023,69841.0,0.106843,0.282827,0.025416,0.261449,7.363376,9.236508,16.748066,0.031124,8.3,10.0,6.7,7.4,14.5,13.3,27.0,39.8,3.7
5,1003,2019,58320.0,0.103541,0.318625,0.042551,0.253245,6.013855,7.551402,15.955104,0.029983,8.6,8.8,7.5,8.4,18.9,11.9,28.5,30.0,3.8
6,1003,2020,61756.0,0.091737,0.319073,0.039175,0.260818,5.306726,7.846903,16.663225,0.028291,8.5,9.5,7.8,8.6,17.5,12.0,24.9,29.7,3.8
7,1003,2021,64346.0,0.092049,0.324503,0.036858,0.270256,5.564162,7.268103,17.631008,0.029702,8.4,9.7,7.4,8.1,14.5,12.6,29.4,37.4,3.5
8,1003,2022,71039.0,0.102140,0.325616,0.034435,0.252771,5.500221,7.317391,18.034498,0.030110,8.2,9.1,8.0,8.4,16.1,12.4,24.7,32.9,3.5
9,1003,2023,75019.0,0.105147,0.327976,0.031943,0.284912,5.485896,7.668363,18.597366,0.033788,10.2,9.3,7.5,7.5,13.0,13.4,25.4,35.2,3.8

## Features and targets split

In [10]:
# Feature groups
raw_features = ['prcSmoking', 'prcObesity', 'prcLPA',
                'PM2_5', 'PM10', 'O3', 'NO2', 'CO']
socioeconomic_features = ['median_household_income', 'poverty_rate',
                          'bachelor_plus_rate', 'unemployment_rate_acs']
baseline_features = raw_features + socioeconomic_features

# Disease targets
disease_targets = [
    'prcCancer_non_skin', 'prcAsthma', 'prcCoronaryHeartDisease',
    'prcCOPD', 'prcDiabetes', 'prcStroke'
]
disease_names = {
    'prcCancer_non_skin': 'Cancer', 'prcAsthma': 'Asthma',
    'prcCoronaryHeartDisease': 'CHD', 'prcCOPD': 'COPD',
    'prcDiabetes': 'Diabetes', 'prcStroke': 'Stroke'
}

print("Features:", baseline_features)
print("Targets:", disease_targets)

Features: ['prcSmoking', 'prcObesity', 'prcLPA', 'PM2_5', 'PM10', 'O3', 'NO2', 'CO', 'median_household_income', 'poverty_rate', 'bachelor_plus_rate', 'unemployment_rate_acs']
Targets: ['prcCancer_non_skin', 'prcAsthma', 'prcCoronaryHeartDisease', 'prcCOPD', 'prcDiabetes', 'prcStroke']

## Train/test data split

In [11]:
train_df = df_full[df_full['year'] <= 2022].copy()   # years 2019–2022
test_df  = df_full[df_full['year'] >= 2023].copy()   # year 2023

print(f"Train size: {len(train_df)} rows (years ≤ 2022)")
print(f"Test size:  {len(test_df)} rows (years ≥ 2023)")

Train size: 12448 rows (years ≤ 2022)
Test size:  2956 rows (years ≥ 2023)

## Create Synthetic Embeddings

In [12]:
def generate_text_description(row, features):
    """Generate a text description from a row of features."""
    parts = []
    for f in features:
        val = row[f]
        # Add simple formatting for readability
        if 'prc' in f:
            parts.append(f"{f} is {val:.2f}%")
        elif 'PM' in f or 'NO2' in f or 'CO' in f or 'O3' in f:
            parts.append(f"{f} concentration is {val:.2f}")
        elif 'income' in f:
            parts.append(f"{f} is ${val:,.0f}")
        else:
            parts.append(f"{f} is {val:.3f}")
    return f"County with FIPS {int(row['FIPS'])}: " + ", ".join(parts)

In [14]:
# Generate texts for train and test sets
print("Generating text descriptions...")
train_texts = train_df.apply(lambda row: generate_text_description(row, baseline_features), axis=1).tolist()
test_texts = test_df.apply(lambda row: generate_text_description(row, baseline_features), axis=1).tolist()

print("Example description for first train sample:")
print(train_texts[0])

Generating text descriptions...
Example description for first train sample:
County with FIPS 1001: prcSmoking is 19.30%, prcObesity is 35.60%, prcLPA is 32.80%, PM2_5 concentration is 8.17, PM10 concentration is 15.73, O3 concentration is 0.03, NO2 concentration is 8.33, CO concentration is 0.28, median_household_income is $58,731, poverty_rate is 0.152, bachelor_plus_rate is 0.266, unemployment_rate_acs is 0.037

In [15]:
# Load a lightweight SentenceTransformer model
print("\nLoading embedding model...")
model = SentenceTransformer('all-MiniLM-L6-v2')
model = model.to('cuda')

Loading embedding model...

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:112: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

AssertionError: Torch not compiled with CUDA enabled

In [ ]:
# Encode texts to embeddings
print("Creating embeddings (this may take a moment)...")
train_embeddings = model.encode(train_texts, show_progress_bar=True)
test_embeddings = model.encode(test_texts, show_progress_bar=True)

Creating embeddings (this may take a moment)...

Batches:   0%|          | 0/389 [00:00<?, ?it/s]

Batches:   0%|          | 0/93 [00:00<?, ?it/s]

In [ ]:
print(f"Train embeddings shape: {train_embeddings.shape}")
print(f"Test embeddings shape:  {test_embeddings.shape}")

Train embeddings shape: (12448, 384)
Test embeddings shape:  (2956, 384)

In [ ]:
test_embeddings

array([[ 0.01371238, -0.02663849, -0.01424895, ..., -0.02212889,
        -0.01929027,  0.03003784],
       [ 0.01075314, -0.02602564, -0.02500538, ..., -0.03596019,
        -0.01652972,  0.03746155],
       [ 0.01248827, -0.03109943, -0.01024241, ..., -0.03519098,
        -0.0127977 ,  0.03481898],
       ...,
       [ 0.00899533, -0.02432484, -0.023468  , ..., -0.03662167,
        -0.02046616,  0.03510575],
       [ 0.0100266 , -0.02488049, -0.02678871, ..., -0.03814025,
        -0.02012893,  0.03650202],
       [ 0.01000481, -0.02900029, -0.01879746, ..., -0.03751006,
        -0.01878037,  0.03404737]], dtype=float32)

In [ ]:
# Add to DataFrames as separate features
# Number of embedding dimensions (384 for MiniLM)
num_emb = train_embeddings.shape[1]
llm_emb_cols = [f'llm_emb_{i+1}' for i in range(num_emb)]

train_emb_df = pd.DataFrame(train_embeddings, columns=llm_emb_cols, index=train_df_emb.index)
test_emb_df  = pd.DataFrame(test_embeddings,  columns=llm_emb_cols, index=test_df_emb.index)

train_df_emb = train_df_emb.join(train_emb_df)
test_df_emb  = test_df_emb.join(test_emb_df)

# Update feature list
llm_features = llm_emb_cols
all_features_with_embeddings = baseline_features + llm_features   # we can also include the synthetic ones, but let's keep clean

print(f"Added {num_emb} LLM‑based embedding features.")
print("New feature set:", all_features_with_embeddings[:5], "...")

Added 384 LLM‑based embedding features.
New feature set: ['prcSmoking', 'prcObesity', 'prcLPA', 'PM2_5', 'PM10'] ...

# Models

## XGBoost

### Evaluations functions

In [ ]:
def weighted_absolute_percentage_error(y_true, y_pred):
    return np.sum(np.abs(y_true - y_pred)) / np.sum(y_true)

def mean_bias(y_true, y_pred):
    return np.mean(y_pred - y_true)

### Training

In [ ]:
# Objective function for Optuna hyperparameter tuning
def objective(trial, X_train, y_train, X_valid, y_valid):
    params = {
        'n_estimators': trial.suggest_int('n_estimators', 100, 500, step=50),
        'max_depth': trial.suggest_int('max_depth', 3, 12),
        'learning_rate': trial.suggest_float('learning_rate', 0.005, 0.1, log=True),
        'subsample': trial.suggest_float('subsample', 0.5, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.5, 1.0),
        'reg_alpha': trial.suggest_float('reg_alpha', 1e-8, 1.0, log=True),
        'reg_lambda': trial.suggest_float('reg_lambda', 1e-8, 1.0, log=True),
        'random_state': 42,
        'verbosity': 0
    }
    model = xgb.XGBRegressor(objective='reg:squarederror', **params)
    model.fit(X_train, y_train, eval_set=[(X_valid, y_valid)], verbose=False)
    y_pred = model.predict(X_valid)
    return r2_score(y_valid, y_pred)

In [ ]:
# Train baseline models for each disease
baseline_results = []

In [ ]:
for target in disease_targets:
    print(f"\n{'='*60}")
    print(f"Training baseline XGBoost for: {disease_names[target]}")

    X_train = train_df_emb[baseline_features]
    y_train = train_df_emb[target]
    X_test = test_df_emb[baseline_features]
    y_test = test_df_emb[target]

    # Hyperparameter tuning
    study = optuna.create_study(direction='maximize', sampler=optuna.samplers.TPESampler(seed=42))
    study.optimize(lambda trial: objective(trial, X_train, y_train, X_test, y_test), n_trials=30, show_progress_bar=False)

    best_params = study.best_params
    print(f"Best params: {best_params}")

    # Train final model
    final_model = xgb.XGBRegressor(objective='reg:squarederror', random_state=42, **best_params)
    final_model.fit(X_train, y_train)

    y_pred = final_model.predict(X_test)
    wape = weighted_absolute_percentage_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)
    bias = mean_bias(y_test, y_pred)

    print(f"Test performance: WAPE={wape:.4f}, R2={r2:.4f}, Bias={bias:.4f}")

    baseline_results.append({
        'Disease': disease_names[target],
        'WAPE': wape,
        'R2': r2,
        'Bias': bias,
        'Model_Type': 'Baseline XGBoost'
    })

[I 2026-06-13 12:56:59,098] A new study created in memory with name: no-name-a6e6e4c6-9ce8-4be6-9dc7-dc3eac5f48bb

============================================================
Training baseline XGBoost for: Cancer

[I 2026-06-13 12:57:12,146] Trial 0 finished with value: -0.509438978501545 and parameters: {'n_estimators': 250, 'max_depth': 12, 'learning_rate': 0.044803926826840625, 'subsample': 0.7993292420985183, 'colsample_bytree': 0.5780093202212182, 'reg_alpha': 1.7699302940633311e-07, 'reg_lambda': 2.9152036385288193e-08}. Best is trial 0 with value: -0.509438978501545.
[I 2026-06-13 12:57:21,092] Trial 1 finished with value: -0.5982594907219967 and parameters: {'n_estimators': 450, 'max_depth': 9, 'learning_rate': 0.04170553216181044, 'subsample': 0.5102922471479012, 'colsample_bytree': 0.9849549260809971, 'reg_alpha': 0.04566054873446119, 'reg_lambda': 4.997040685255803e-07}. Best is trial 0 with value: -0.509438978501545.
[I 2026-06-13 12:57:21,542] Trial 2 finished with value: -0.5904376960584696 and parameters: {'n_estimators': 150, 'max_depth': 4, 'learning_rate': 0.012439367209907218, 'subsample': 0.762378215816119, 'colsample_bytree': 0.7159725093210578, 'reg_alpha': 2.1371407316372935e-06, 'reg_lambda': 0.000784915956255507}. Best is trial 0 with value: -0.509438978501545.
[I 2026-06-13 12:57:22,174] Trial 3 finished with value: -0.6376772321154716 and parameters: {'n_estimators': 150, 'max_depth': 5, 'learning_rate': 0.014983654548550792, 'subsample': 0.728034992108518, 'colsample_bytree': 0.8925879806965068, 'reg_alpha': 3.9572205641009174e-07, 'reg_lambda': 0.00012997969313168238}. Best is trial 0 with value: -0.509438978501545.
[I 2026-06-13 12:57:24,766] Trial 4 finished with value: -0.731191734613482 and parameters: {'n_estimators': 350, 'max_depth': 3, 'learning_rate': 0.030860579740535368, 'subsample': 0.5852620618436457, 'colsample_bytree': 0.5325257964926398, 'reg_alpha': 0.39001768308022033, 'reg_lambda': 0.530953226900921}. Best is trial 0 with value: -0.509438978501545.
[I 2026-06-13 12:57:27,051] Trial 5 finished with value: -0.652889512811303 and parameters: {'n_estimators': 450, 'max_depth': 6, 'learning_rate': 0.006699530280754897, 'subsample': 0.8421165132560784, 'colsample_bytree': 0.7200762468698007, 'reg_alpha': 9.469038421774442e-08, 'reg_lambda': 9.149877525022172e-05}. Best is trial 0 with value: -0.509438978501545.
[I 2026-06-13 12:57:32,177] Trial 6 finished with value: -0.4886753695070922 and parameters: {'n_estimators': 100, 'max_depth': 12, 'learning_rate': 0.010855517271883068, 'subsample': 0.831261142176991, 'colsample_bytree': 0.6558555380447055, 'reg_alpha': 0.00014472520367197597, 'reg_lambda': 0.00023641892308789696}. Best is trial 6 with value: -0.4886753695070922.
[I 2026-06-13 12:57:43,444] Trial 7 finished with value: -0.6539632574003544 and parameters: {'n_estimators': 150, 'max_depth': 12, 'learning_rate': 0.05098483969585744, 'subsample': 0.9697494707820946, 'colsample_bytree': 0.9474136752138245, 'reg_alpha': 0.0006070155694141794, 'reg_lambda': 0.23713402899336497}. Best is trial 6 with value: -0.4886753695070922.
[I 2026-06-13 12:57:43,742] Trial 8 finished with value: -0.5513867654300284 and parameters: {'n_estimators': 100, 'max_depth': 4, 'learning_rate': 0.005725482134163321, 'subsample': 0.6626651653816322, 'colsample_bytree': 0.6943386448447411, 'reg_alpha': 1.481809088646707e-06, 'reg_lambda': 0.04264813784432918}. Best is trial 6 with value: -0.4886753695070922.
[I 2026-06-13 12:57:44,763] Trial 9 finished with value: -0.6922438737576253 and parameters: {'n_estimators': 250, 'max_depth': 5, 'learning_rate': 0.025411709798607296, 'subsample': 0.5704621124873813, 'colsample_bytree': 0.9010984903770198, 'reg_alpha': 3.9482545946332394e-08, 'reg_lambda': 0.7854083114461319}. Best is trial 6 with value: -0.4886753695070922.
[I 2026-06-13 12:57:52,245] Trial 10 finished with value: -0.5852316129190516 and parameters: {'n_estimators': 500, 'max_depth': 8, 'learning_rate': 0.09127815799510323, 'subsample': 0.9661451709558936, 'colsample_bytree': 0.8200442512337782, 'reg_alpha': 0.0001373650144373192, 'reg_lambda': 3.437797669408157e-06}. Best is trial 6 with value: -0.4886753695070922.
[I 2026-06-13 12:58:03,811] Trial 11 finished with value: -0.5580247771748437 and parameters: {'n_estimators': 250, 'max_depth': 12, 'learning_rate': 0.0947693247311395, 'subsample': 0.8591901910708762, 'colsample_bytree': 0.5535604140382236, 'reg_alpha': 4.997544746782185e-05, 'reg_lambda': 3.311752327271811e-08}. Best is trial 6 with value: -0.4886753695070922.
[I 2026-06-13 12:58:10,877] Trial 12 finished with value: -0.5475795145776325 and parameters: {'n_estimators': 250, 'max_depth': 10, 'learning_rate': 0.016777837804937287, 'subsample': 0.8364610680219806, 'colsample_bytree': 0.6135020205326719, 'reg_alpha': 0.004241771490270244, 'reg_lambda': 4.9984666298388584e-08}. Best is trial 6 with value: -0.4886753695070922.
[I 2026-06-13 12:58:27,736] Trial 13 finished with value: -0.5281152098469832 and parameters: {'n_estimators': 350, 'max_depth': 11, 'learning_rate': 0.007915289741986391, 'subsample': 0.7698100534013989, 'colsample_bytree': 0.6352453073825163, 'reg_alpha': 1.3082115243148923e-05, 'reg_lambda': 0.00496389307183381}. Best is trial 6 with value: -0.4886753695070922.
[I 2026-06-13 12:58:35,801] Trial 14 finished with value: -0.5871717518259558 and parameters: {'n_estimators': 300, 'max_depth': 10, 'learning_rate': 0.05799375627384968, 'subsample': 0.908898510280282, 'colsample_bytree': 0.6123366282341044, 'reg_alpha': 2.037134057581659e-08, 'reg_lambda': 5.688159178078768e-06}. Best is trial 6 with value: -0.4886753695070922.
[I 2026-06-13 12:58:41,213] Trial 15 finished with value: -0.48200750001740555 and parameters: {'n_estimators': 100, 'max_depth': 12, 'learning_rate': 0.010256126071863714, 'subsample': 0.6978659270798593, 'colsample_bytree': 0.5031267798537731, 'reg_alpha': 0.0011185998282529164, 'reg_lambda': 1.1426317436115783e-06}. Best is trial 15 with value: -0.48200750001740555.
[I 2026-06-13 12:58:44,756] Trial 16 finished with value: -0.5524166883064334 and parameters: {'n_estimators': 100, 'max_depth': 10, 'learning_rate': 0.009616149538336718, 'subsample': 0.6924745509172271, 'colsample_bytree': 0.7897830247330323, 'reg_alpha': 0.00252814495846281, 'reg_lambda': 1.276925019838971e-05}. Best is trial 15 with value: -0.48200750001740555.
[I 2026-06-13 12:58:45,720] Trial 17 finished with value: -0.5189531315961442 and parameters: {'n_estimators': 100, 'max_depth': 8, 'learning_rate': 0.020647347380177827, 'subsample': 0.6430104032327739, 'colsample_bytree': 0.5239511636127645, 'reg_alpha': 0.010614622828552219, 'reg_lambda': 5.251824672263031e-07}. Best is trial 15 with value: -0.48200750001740555.
[I 2026-06-13 12:58:51,931] Trial 18 finished with value: -0.49658140866290523 and parameters: {'n_estimators': 200, 'max_depth': 11, 'learning_rate': 0.01073511996371044, 'subsample': 0.7205048899037588, 'colsample_bytree': 0.5002864556458626, 'reg_alpha': 0.00029986594356080703, 'reg_lambda': 0.0021492409884522746}. Best is trial 15 with value: -0.48200750001740555.
[I 2026-06-13 12:59:01,245] Trial 19 finished with value: -0.509650110324811 and parameters: {'n_estimators': 200, 'max_depth': 11, 'learning_rate': 0.005367826196356391, 'subsample': 0.8910338943896522, 'colsample_bytree': 0.6602765812234954, 'reg_alpha': 1.1001750991059728e-05, 'reg_lambda': 0.00011329482031728177}. Best is trial 15 with value: -0.48200750001740555.
[I 2026-06-13 12:59:02,519] Trial 20 finished with value: -0.5666989838807834 and parameters: {'n_estimators': 100, 'max_depth': 8, 'learning_rate': 0.009228907348324331, 'subsample': 0.6211956468784469, 'colsample_bytree': 0.7752847229001598, 'reg_alpha': 0.15141615482681153, 'reg_lambda': 3.593006567943814e-07}. Best is trial 15 with value: -0.48200750001740555.
[I 2026-06-13 12:59:10,345] Trial 21 finished with value: -0.5069439763604695 and parameters: {'n_estimators': 200, 'max_depth': 11, 'learning_rate': 0.011232797112998065, 'subsample': 0.7013008348404328, 'colsample_bytree': 0.5008013240402124, 'reg_alpha': 0.00042552077030641157, 'reg_lambda': 0.004016746147408668}. Best is trial 15 with value: -0.48200750001740555.
[I 2026-06-13 12:59:21,035] Trial 22 finished with value: -0.49138830047791227 and parameters: {'n_estimators': 200, 'max_depth': 12, 'learning_rate': 0.013095644745476455, 'subsample': 0.7462188412574724, 'colsample_bytree': 0.5761088507158494, 'reg_alpha': 0.0006834958672191868, 'reg_lambda': 0.0015371004607217902}. Best is trial 15 with value: -0.48200750001740555.
[I 2026-06-13 12:59:27,705] Trial 23 finished with value: -0.48645291585351247 and parameters: {'n_estimators': 150, 'max_depth': 12, 'learning_rate': 0.015523150651775286, 'subsample': 0.7842594158358256, 'colsample_bytree': 0.5788305088622605, 'reg_alpha': 0.0016739010222431379, 'reg_lambda': 0.017436674931954606}. Best is trial 15 with value: -0.48200750001740555.
[I 2026-06-13 12:59:36,623] Trial 24 finished with value: -0.5265115311855364 and parameters: {'n_estimators': 150, 'max_depth': 12, 'learning_rate': 0.018627898567474398, 'subsample': 0.7985223375197199, 'colsample_bytree': 0.6550432118792029, 'reg_alpha': 0.03945843181311371, 'reg_lambda': 0.048914160834551856}. Best is trial 15 with value: -0.48200750001740555.
[I 2026-06-13 12:59:39,165] Trial 25 finished with value: -0.5106697262668727 and parameters: {'n_estimators': 100, 'max_depth': 10, 'learning_rate': 0.007546325194803134, 'subsample': 0.8032237938522335, 'colsample_bytree': 0.5895340876570929, 'reg_alpha': 3.047426595980065e-05, 'reg_lambda': 0.019431765464167274}. Best is trial 15 with value: -0.48200750001740555.
[I 2026-06-13 12:59:47,327] Trial 26 finished with value: -0.606213793313269 and parameters: {'n_estimators': 150, 'max_depth': 11, 'learning_rate': 0.0264326323886436, 'subsample': 0.8774659562071867, 'colsample_bytree': 0.682635976821535, 'reg_alpha': 0.003530885575899875, 'reg_lambda': 0.0004181505505162669}. Best is trial 15 with value: -0.48200750001740555.
[I 2026-06-13 12:59:48,896] Trial 27 finished with value: -0.49327502012961366 and parameters: {'n_estimators': 100, 'max_depth': 9, 'learning_rate': 0.014039845492051846, 'subsample': 0.9129087307405539, 'colsample_bytree': 0.5518855989374114, 'reg_alpha': 9.819176016525168e-05, 'reg_lambda': 3.2154898554057994e-05}. Best is trial 15 with value: -0.48200750001740555.
[I 2026-06-13 12:59:58,712] Trial 28 finished with value: -0.5044568580425652 and parameters: {'n_estimators': 150, 'max_depth': 12, 'learning_rate': 0.008516359258968495, 'subsample': 0.6707391952450417, 'colsample_bytree': 0.6192025152452842, 'reg_alpha': 0.01343790502191945, 'reg_lambda': 0.014279701206211892}. Best is trial 15 with value: -0.48200750001740555.
[I 2026-06-13 13:00:11,357] Trial 29 finished with value: -0.5426557248560926 and parameters: {'n_estimators': 200, 'max_depth': 12, 'learning_rate': 0.02123749506610946, 'subsample': 0.8016289779967308, 'colsample_bytree': 0.5848712441801299, 'reg_alpha': 0.0008252621543703961, 'reg_lambda': 2.5894564150350493e-06}. Best is trial 15 with value: -0.48200750001740555.

Best params: {'n_estimators': 100, 'max_depth': 12, 'learning_rate': 0.010256126071863714, 'subsample': 0.6978659270798593, 'colsample_bytree': 0.5031267798537731, 'reg_alpha': 0.0011185998282529164, 'reg_lambda': 1.1426317436115783e-06}

[I 2026-06-13 13:00:15,613] A new study created in memory with name: no-name-e8c143cd-0ed1-4120-a762-b606dfbbf168

Test performance: WAPE=0.1854, R2=-0.4820, Bias=-1.4180

============================================================
Training baseline XGBoost for: Asthma

[I 2026-06-13 13:00:29,537] Trial 0 finished with value: -0.24947795027635888 and parameters: {'n_estimators': 250, 'max_depth': 12, 'learning_rate': 0.044803926826840625, 'subsample': 0.7993292420985183, 'colsample_bytree': 0.5780093202212182, 'reg_alpha': 1.7699302940633311e-07, 'reg_lambda': 2.9152036385288193e-08}. Best is trial 0 with value: -0.24947795027635888.
[I 2026-06-13 13:00:39,963] Trial 1 finished with value: -0.18670788118425574 and parameters: {'n_estimators': 450, 'max_depth': 9, 'learning_rate': 0.04170553216181044, 'subsample': 0.5102922471479012, 'colsample_bytree': 0.9849549260809971, 'reg_alpha': 0.04566054873446119, 'reg_lambda': 4.997040685255803e-07}. Best is trial 1 with value: -0.18670788118425574.
[I 2026-06-13 13:00:40,401] Trial 2 finished with value: -0.46212387094832885 and parameters: {'n_estimators': 150, 'max_depth': 4, 'learning_rate': 0.012439367209907218, 'subsample': 0.762378215816119, 'colsample_bytree': 0.7159725093210578, 'reg_alpha': 2.1371407316372935e-06, 'reg_lambda': 0.000784915956255507}. Best is trial 1 with value: -0.18670788118425574.
[I 2026-06-13 13:00:41,064] Trial 3 finished with value: -0.3961058136950659 and parameters: {'n_estimators': 150, 'max_depth': 5, 'learning_rate': 0.014983654548550792, 'subsample': 0.728034992108518, 'colsample_bytree': 0.8925879806965068, 'reg_alpha': 3.9572205641009174e-07, 'reg_lambda': 0.00012997969313168238}. Best is trial 1 with value: -0.18670788118425574.
[I 2026-06-13 13:00:41,807] Trial 4 finished with value: -0.3669891014923752 and parameters: {'n_estimators': 350, 'max_depth': 3, 'learning_rate': 0.030860579740535368, 'subsample': 0.5852620618436457, 'colsample_bytree': 0.5325257964926398, 'reg_alpha': 0.39001768308022033, 'reg_lambda': 0.530953226900921}. Best is trial 1 with value: -0.18670788118425574.
[I 2026-06-13 13:00:44,243] Trial 5 finished with value: -0.29669145113093354 and parameters: {'n_estimators': 450, 'max_depth': 6, 'learning_rate': 0.006699530280754897, 'subsample': 0.8421165132560784, 'colsample_bytree': 0.7200762468698007, 'reg_alpha': 9.469038421774442e-08, 'reg_lambda': 9.149877525022172e-05}. Best is trial 1 with value: -0.18670788118425574.
[I 2026-06-13 13:00:52,204] Trial 6 finished with value: -0.27277839759177747 and parameters: {'n_estimators': 100, 'max_depth': 12, 'learning_rate': 0.010855517271883068, 'subsample': 0.831261142176991, 'colsample_bytree': 0.6558555380447055, 'reg_alpha': 0.00014472520367197597, 'reg_lambda': 0.00023641892308789696}. Best is trial 1 with value: -0.18670788118425574.
[I 2026-06-13 13:01:05,204] Trial 7 finished with value: -0.17550269421356113 and parameters: {'n_estimators': 150, 'max_depth': 12, 'learning_rate': 0.05098483969585744, 'subsample': 0.9697494707820946, 'colsample_bytree': 0.9474136752138245, 'reg_alpha': 0.0006070155694141794, 'reg_lambda': 0.23713402899336497}. Best is trial 7 with value: -0.17550269421356113.
[I 2026-06-13 13:01:05,511] Trial 8 finished with value: -0.4862430750843023 and parameters: {'n_estimators': 100, 'max_depth': 4, 'learning_rate': 0.005725482134163321, 'subsample': 0.6626651653816322, 'colsample_bytree': 0.6943386448447411, 'reg_alpha': 1.481809088646707e-06, 'reg_lambda': 0.04264813784432918}. Best is trial 7 with value: -0.17550269421356113.
[I 2026-06-13 13:01:06,557] Trial 9 finished with value: -0.2909119261352846 and parameters: {'n_estimators': 250, 'max_depth': 5, 'learning_rate': 0.025411709798607296, 'subsample': 0.5704621124873813, 'colsample_bytree': 0.9010984903770198, 'reg_alpha': 3.9482545946332394e-08, 'reg_lambda': 0.7854083114461319}. Best is trial 7 with value: -0.17550269421356113.
[I 2026-06-13 13:01:13,191] Trial 10 finished with value: -0.19938508891329576 and parameters: {'n_estimators': 500, 'max_depth': 8, 'learning_rate': 0.09127815799510323, 'subsample': 0.9674347845165696, 'colsample_bytree': 0.8200442512337782, 'reg_alpha': 0.00039963593659993017, 'reg_lambda': 1.1572191738342066e-06}. Best is trial 7 with value: -0.17550269421356113.
[I 2026-06-13 13:01:24,189] Trial 11 finished with value: -0.20491849032583942 and parameters: {'n_estimators': 350, 'max_depth': 10, 'learning_rate': 0.07496095461648841, 'subsample': 0.9945249506801312, 'colsample_bytree': 0.9789145912933507, 'reg_alpha': 0.05556041446700225, 'reg_lambda': 1.140193722241888e-06}. Best is trial 7 with value: -0.17550269421356113.
[I 2026-06-13 13:01:33,951] Trial 12 finished with value: -0.18944171877891924 and parameters: {'n_estimators': 400, 'max_depth': 9, 'learning_rate': 0.05054047110262676, 'subsample': 0.5093874207968743, 'colsample_bytree': 0.9772402514753298, 'reg_alpha': 0.004887825563866239, 'reg_lambda': 0.019472772732431278}. Best is trial 7 with value: -0.17550269421356113.
[I 2026-06-13 13:01:43,342] Trial 13 finished with value: -0.191516266306478 and parameters: {'n_estimators': 250, 'max_depth': 10, 'learning_rate': 0.0494459671681148, 'subsample': 0.8970314217584594, 'colsample_bytree': 0.8843449380234663, 'reg_alpha': 8.767548377334874e-05, 'reg_lambda': 2.702201695017823e-08}. Best is trial 7 with value: -0.17550269421356113.
[I 2026-06-13 13:01:47,251] Trial 14 finished with value: -0.22319752705725393 and parameters: {'n_estimators': 500, 'max_depth': 7, 'learning_rate': 0.02711641797158028, 'subsample': 0.6852641649889502, 'colsample_bytree': 0.818347963953445, 'reg_alpha': 0.006238181279781729, 'reg_lambda': 3.146874964808016e-06}. Best is trial 7 with value: -0.17550269421356113.
[I 2026-06-13 13:01:59,526] Trial 15 finished with value: -0.18219441568514827 and parameters: {'n_estimators': 300, 'max_depth': 11, 'learning_rate': 0.06457337851873803, 'subsample': 0.9171981962581279, 'colsample_bytree': 0.9980084946806067, 'reg_alpha': 0.9375555540175456, 'reg_lambda': 0.003061524575248242}. Best is trial 7 with value: -0.17550269421356113.
[I 2026-06-13 13:02:09,455] Trial 16 finished with value: -0.20949781059218986 and parameters: {'n_estimators': 200, 'max_depth': 11, 'learning_rate': 0.07554879581747483, 'subsample': 0.9160835704673446, 'colsample_bytree': 0.9297279549046962, 'reg_alpha': 0.5677521877558732, 'reg_lambda': 0.007362495946068417}. Best is trial 7 with value: -0.17550269421356113.
[I 2026-06-13 13:02:22,959] Trial 17 finished with value: -0.22252694625777436 and parameters: {'n_estimators': 300, 'max_depth': 11, 'learning_rate': 0.06632302621180221, 'subsample': 0.9191904809865727, 'colsample_bytree': 0.8211810280697476, 'reg_alpha': 0.0013107633024511203, 'reg_lambda': 0.002007571206937617}. Best is trial 7 with value: -0.17550269421356113.
[I 2026-06-13 13:02:43,192] Trial 18 finished with value: -0.1865846595447651 and parameters: {'n_estimators': 200, 'max_depth': 12, 'learning_rate': 0.020923562222087386, 'subsample': 0.8754986180062629, 'colsample_bytree': 0.938797907659533, 'reg_alpha': 1.2887051328367313e-05, 'reg_lambda': 0.1014265638962444}. Best is trial 7 with value: -0.17550269421356113.
[I 2026-06-13 13:02:58,093] Trial 19 finished with value: -0.17319457826143703 and parameters: {'n_estimators': 300, 'max_depth': 11, 'learning_rate': 0.0353770014325364, 'subsample': 0.9526989680517983, 'colsample_bytree': 0.8448372126058836, 'reg_alpha': 0.07529078658925144, 'reg_lambda': 0.13979175712376057}. Best is trial 19 with value: -0.17319457826143703.
[I 2026-06-13 13:03:03,275] Trial 20 finished with value: -0.20903164054501144 and parameters: {'n_estimators': 150, 'max_depth': 10, 'learning_rate': 0.01793328314292978, 'subsample': 0.960166660531481, 'colsample_bytree': 0.7752847229001598, 'reg_alpha': 0.048226962295075226, 'reg_lambda': 0.13916335528315113}. Best is trial 19 with value: -0.17319457826143703.
[I 2026-06-13 13:03:16,591] Trial 21 finished with value: -0.17143163417749818 and parameters: {'n_estimators': 300, 'max_depth': 11, 'learning_rate': 0.03562356466103217, 'subsample': 0.9463033699059225, 'colsample_bytree': 0.8651735209467732, 'reg_alpha': 0.7758745624237906, 'reg_lambda': 0.006990888519938072}. Best is trial 21 with value: -0.17143163417749818.
[I 2026-06-13 13:03:34,697] Trial 22 finished with value: -0.17604282995190212 and parameters: {'n_estimators': 350, 'max_depth': 11, 'learning_rate': 0.035243955882160234, 'subsample': 0.993126342073174, 'colsample_bytree': 0.8726895797206472, 'reg_alpha': 0.1304383441044463, 'reg_lambda': 0.19709783465073125}. Best is trial 21 with value: -0.17143163417749818.
[I 2026-06-13 13:03:40,281] Trial 23 finished with value: -0.19959968503916903 and parameters: {'n_estimators': 300, 'max_depth': 9, 'learning_rate': 0.03499071236248988, 'subsample': 0.9470787733907856, 'colsample_bytree': 0.7783658553128417, 'reg_alpha': 0.008481690504257953, 'reg_lambda': 0.017714506907356733}. Best is trial 21 with value: -0.17143163417749818.
[I 2026-06-13 13:03:54,337] Trial 24 finished with value: -0.17494647590222145 and parameters: {'n_estimators': 200, 'max_depth': 12, 'learning_rate': 0.05592639354663567, 'subsample': 0.8647983622203373, 'colsample_bytree': 0.8412412790940987, 'reg_alpha': 0.011777944382300745, 'reg_lambda': 0.041601141098396584}. Best is trial 21 with value: -0.17143163417749818.
[I 2026-06-13 13:04:03,385] Trial 25 finished with value: -0.1734845946258008 and parameters: {'n_estimators': 200, 'max_depth': 10, 'learning_rate': 0.021298576444817172, 'subsample': 0.8673890146609609, 'colsample_bytree': 0.8508925643633427, 'reg_alpha': 0.01678231410193124, 'reg_lambda': 0.0007443434956826249}. Best is trial 21 with value: -0.17143163417749818.
[I 2026-06-13 13:04:07,319] Trial 26 finished with value: -0.2054707532751161 and parameters: {'n_estimators': 300, 'max_depth': 8, 'learning_rate': 0.020324467380845278, 'subsample': 0.8106452018417596, 'colsample_bytree': 0.7764123044504091, 'reg_alpha': 0.1994279058877706, 'reg_lambda': 2.0705800917648828e-05}. Best is trial 21 with value: -0.17143163417749818.
[I 2026-06-13 13:04:25,291] Trial 27 finished with value: -0.181206807712879 and parameters: {'n_estimators': 400, 'max_depth': 10, 'learning_rate': 0.009927102764022071, 'subsample': 0.8834154000735982, 'colsample_bytree': 0.862580774849707, 'reg_alpha': 0.031902296253764395, 'reg_lambda': 0.0011806031580191242}. Best is trial 21 with value: -0.17143163417749818.
[I 2026-06-13 13:04:28,594] Trial 28 finished with value: -0.21877679179795329 and parameters: {'n_estimators': 250, 'max_depth': 8, 'learning_rate': 0.024550782171073243, 'subsample': 0.9358422325535489, 'colsample_bytree': 0.7589502873761826, 'reg_alpha': 0.002074459477410359, 'reg_lambda': 0.005972599575925503}. Best is trial 21 with value: -0.17143163417749818.
[I 2026-06-13 13:04:39,392] Trial 29 finished with value: -0.13874883845884756 and parameters: {'n_estimators': 200, 'max_depth': 11, 'learning_rate': 0.03501913221240992, 'subsample': 0.7729130885427475, 'colsample_bytree': 0.8459844036224798, 'reg_alpha': 0.12512929956640986, 'reg_lambda': 0.0004614135530265186}. Best is trial 29 with value: -0.13874883845884756.

Best params: {'n_estimators': 200, 'max_depth': 11, 'learning_rate': 0.03501913221240992, 'subsample': 0.7729130885427475, 'colsample_bytree': 0.8459844036224798, 'reg_alpha': 0.12512929956640986, 'reg_lambda': 0.0004614135530265186}

[I 2026-06-13 13:04:50,014] A new study created in memory with name: no-name-954a98d3-faa1-4675-8979-02926850a9eb

Test performance: WAPE=0.0725, R2=-0.1387, Bias=-0.7015

============================================================
Training baseline XGBoost for: CHD

[I 2026-06-13 13:05:03,425] Trial 0 finished with value: 0.5122796314426761 and parameters: {'n_estimators': 250, 'max_depth': 12, 'learning_rate': 0.044803926826840625, 'subsample': 0.7993292420985183, 'colsample_bytree': 0.5780093202212182, 'reg_alpha': 1.7699302940633311e-07, 'reg_lambda': 2.9152036385288193e-08}. Best is trial 0 with value: 0.5122796314426761.
[I 2026-06-13 13:05:13,967] Trial 1 finished with value: 0.4093216746336238 and parameters: {'n_estimators': 450, 'max_depth': 9, 'learning_rate': 0.04170553216181044, 'subsample': 0.5102922471479012, 'colsample_bytree': 0.9849549260809971, 'reg_alpha': 0.04566054873446119, 'reg_lambda': 4.997040685255803e-07}. Best is trial 0 with value: 0.5122796314426761.
[I 2026-06-13 13:05:14,460] Trial 2 finished with value: 0.5184430376304726 and parameters: {'n_estimators': 150, 'max_depth': 4, 'learning_rate': 0.012439367209907218, 'subsample': 0.762378215816119, 'colsample_bytree': 0.7159725093210578, 'reg_alpha': 2.1371407316372935e-06, 'reg_lambda': 0.000784915956255507}. Best is trial 2 with value: 0.5184430376304726.
[I 2026-06-13 13:05:15,098] Trial 3 finished with value: 0.5001869542002682 and parameters: {'n_estimators': 150, 'max_depth': 5, 'learning_rate': 0.014983654548550792, 'subsample': 0.728034992108518, 'colsample_bytree': 0.8925879806965068, 'reg_alpha': 3.9572205641009174e-07, 'reg_lambda': 0.00012997969313168238}. Best is trial 2 with value: 0.5184430376304726.
[I 2026-06-13 13:05:15,846] Trial 4 finished with value: 0.4438014292811143 and parameters: {'n_estimators': 350, 'max_depth': 3, 'learning_rate': 0.030860579740535368, 'subsample': 0.5852620618436457, 'colsample_bytree': 0.5325257964926398, 'reg_alpha': 0.39001768308022033, 'reg_lambda': 0.530953226900921}. Best is trial 2 with value: 0.5184430376304726.
[I 2026-06-13 13:05:18,181] Trial 5 finished with value: 0.4848718095108365 and parameters: {'n_estimators': 450, 'max_depth': 6, 'learning_rate': 0.006699530280754897, 'subsample': 0.8421165132560784, 'colsample_bytree': 0.7200762468698007, 'reg_alpha': 9.469038421774442e-08, 'reg_lambda': 9.149877525022172e-05}. Best is trial 2 with value: 0.5184430376304726.
[I 2026-06-13 13:05:25,774] Trial 6 finished with value: 0.5051251007261681 and parameters: {'n_estimators': 100, 'max_depth': 12, 'learning_rate': 0.010855517271883068, 'subsample': 0.831261142176991, 'colsample_bytree': 0.6558555380447055, 'reg_alpha': 0.00014472520367197597, 'reg_lambda': 0.00023641892308789696}. Best is trial 2 with value: 0.5184430376304726.
[I 2026-06-13 13:05:39,212] Trial 7 finished with value: 0.39859001649657544 and parameters: {'n_estimators': 150, 'max_depth': 12, 'learning_rate': 0.05098483969585744, 'subsample': 0.9697494707820946, 'colsample_bytree': 0.9474136752138245, 'reg_alpha': 0.0006070155694141794, 'reg_lambda': 0.23713402899336497}. Best is trial 2 with value: 0.5184430376304726.
[I 2026-06-13 13:05:39,519] Trial 8 finished with value: 0.3595768047086937 and parameters: {'n_estimators': 100, 'max_depth': 4, 'learning_rate': 0.005725482134163321, 'subsample': 0.6626651653816322, 'colsample_bytree': 0.6943386448447411, 'reg_alpha': 1.481809088646707e-06, 'reg_lambda': 0.04264813784432918}. Best is trial 2 with value: 0.5184430376304726.
[I 2026-06-13 13:05:40,526] Trial 9 finished with value: 0.41019019805942747 and parameters: {'n_estimators': 250, 'max_depth': 5, 'learning_rate': 0.025411709798607296, 'subsample': 0.5704621124873813, 'colsample_bytree': 0.9010984903770198, 'reg_alpha': 3.9482545946332394e-08, 'reg_lambda': 0.7854083114461319}. Best is trial 2 with value: 0.5184430376304726.
[I 2026-06-13 13:05:46,277] Trial 10 finished with value: 0.3939809657658472 and parameters: {'n_estimators': 500, 'max_depth': 8, 'learning_rate': 0.09127815799510323, 'subsample': 0.9661451709558936, 'colsample_bytree': 0.7978634791402932, 'reg_alpha': 2.4201010269271677e-05, 'reg_lambda': 0.004456706686912844}. Best is trial 2 with value: 0.5184430376304726.
[I 2026-06-13 13:05:51,813] Trial 11 finished with value: 0.5130190621397714 and parameters: {'n_estimators': 250, 'max_depth': 9, 'learning_rate': 0.015590014226761156, 'subsample': 0.7890156464146867, 'colsample_bytree': 0.5268923276740406, 'reg_alpha': 4.4287724067533044e-06, 'reg_lambda': 3.655344221640593e-08}. Best is trial 2 with value: 0.5184430376304726.
[I 2026-06-13 13:05:55,558] Trial 12 finished with value: 0.5248987942703922 and parameters: {'n_estimators': 250, 'max_depth': 9, 'learning_rate': 0.012699566471214473, 'subsample': 0.7349716074984779, 'colsample_bytree': 0.5069746357482796, 'reg_alpha': 1.1870339856511064e-05, 'reg_lambda': 2.7546889151221635e-06}. Best is trial 12 with value: 0.5248987942703922.
[I 2026-06-13 13:05:57,314] Trial 13 finished with value: 0.5132826037278091 and parameters: {'n_estimators': 200, 'max_depth': 7, 'learning_rate': 0.009167593205453134, 'subsample': 0.6985683607485169, 'colsample_bytree': 0.7894426605229882, 'reg_alpha': 0.0001648471264431708, 'reg_lambda': 3.0124140872167842e-06}. Best is trial 12 with value: 0.5248987942703922.
[I 2026-06-13 13:06:04,892] Trial 14 finished with value: 0.46992402728563765 and parameters: {'n_estimators': 350, 'max_depth': 9, 'learning_rate': 0.018577637922759307, 'subsample': 0.9056421932528459, 'colsample_bytree': 0.6123366282341044, 'reg_alpha': 0.002028856958783279, 'reg_lambda': 3.963605810657602e-06}. Best is trial 12 with value: 0.5248987942703922.
[I 2026-06-13 13:06:17,746] Trial 15 finished with value: 0.47377999781261926 and parameters: {'n_estimators': 350, 'max_depth': 10, 'learning_rate': 0.009899241847965298, 'subsample': 0.731057379200564, 'colsample_bytree': 0.7704051283922909, 'reg_alpha': 9.027057239538086e-06, 'reg_lambda': 0.0016211509246398057}. Best is trial 12 with value: 0.5248987942703922.
[I 2026-06-13 13:06:19,815] Trial 16 finished with value: 0.4513757167293191 and parameters: {'n_estimators': 300, 'max_depth': 7, 'learning_rate': 0.02199163418016887, 'subsample': 0.6614121398245355, 'colsample_bytree': 0.6259163470770788, 'reg_alpha': 1.1142799962646395e-08, 'reg_lambda': 9.813448460510674e-06}. Best is trial 12 with value: 0.5248987942703922.
[I 2026-06-13 13:06:28,356] Trial 17 finished with value: 0.48331909706466625 and parameters: {'n_estimators': 200, 'max_depth': 10, 'learning_rate': 0.011576964537034107, 'subsample': 0.8805304594988683, 'colsample_bytree': 0.8382122499277462, 'reg_alpha': 0.005155331400801696, 'reg_lambda': 2.1928421976024512e-07}. Best is trial 12 with value: 0.5248987942703922.
[I 2026-06-13 13:06:29,392] Trial 18 finished with value: 0.44889091196163966 and parameters: {'n_estimators': 150, 'max_depth': 3, 'learning_rate': 0.0067733539129048986, 'subsample': 0.7615909739551969, 'colsample_bytree': 0.5003894611458092, 'reg_alpha': 5.4209011109757376e-05, 'reg_lambda': 0.004555336510944913}. Best is trial 12 with value: 0.5248987942703922.
[I 2026-06-13 13:06:30,210] Trial 19 finished with value: 0.4978865963225654 and parameters: {'n_estimators': 200, 'max_depth': 5, 'learning_rate': 0.01384640594801836, 'subsample': 0.6219197140707918, 'colsample_bytree': 0.7153949344598675, 'reg_alpha': 9.372280034723041e-07, 'reg_lambda': 5.4978635376147394e-05}. Best is trial 12 with value: 0.5248987942703922.
[I 2026-06-13 13:06:32,480] Trial 20 finished with value: 0.5244477957769298 and parameters: {'n_estimators': 300, 'max_depth': 7, 'learning_rate': 0.007545614592715071, 'subsample': 0.8979338809467865, 'colsample_bytree': 0.5916526779070379, 'reg_alpha': 3.7555260992304618e-06, 'reg_lambda': 0.0006811902073532948}. Best is trial 12 with value: 0.5248987942703922.
[I 2026-06-13 13:06:34,545] Trial 21 finished with value: 0.5342843042476526 and parameters: {'n_estimators': 300, 'max_depth': 7, 'learning_rate': 0.0077395895303364074, 'subsample': 0.904152350085489, 'colsample_bytree': 0.5778043367890922, 'reg_alpha': 4.6025199735396895e-06, 'reg_lambda': 0.034062941139685526}. Best is trial 21 with value: 0.5342843042476526.
[I 2026-06-13 13:06:36,575] Trial 22 finished with value: 0.532360197794534 and parameters: {'n_estimators': 300, 'max_depth': 7, 'learning_rate': 0.008028633857090574, 'subsample': 0.9225250957373745, 'colsample_bytree': 0.5710717914265592, 'reg_alpha': 1.3493720418043794e-05, 'reg_lambda': 0.03507972672524241}. Best is trial 21 with value: 0.5342843042476526.
[I 2026-06-13 13:06:39,914] Trial 23 finished with value: 0.5306454828596326 and parameters: {'n_estimators': 300, 'max_depth': 8, 'learning_rate': 0.005052017214628772, 'subsample': 0.9991965233048097, 'colsample_bytree': 0.5598306757070644, 'reg_alpha': 1.209424293449493e-05, 'reg_lambda': 0.03118698988309067}. Best is trial 21 with value: 0.5342843042476526.
[I 2026-06-13 13:06:45,605] Trial 24 finished with value: 0.536921689402406 and parameters: {'n_estimators': 400, 'max_depth': 8, 'learning_rate': 0.005322249973929488, 'subsample': 0.9385120515287855, 'colsample_bytree': 0.5673139316598559, 'reg_alpha': 7.962995692272208e-05, 'reg_lambda': 0.034284794851948165}. Best is trial 24 with value: 0.536921689402406.
[I 2026-06-13 13:06:47,771] Trial 25 finished with value: 0.48119315218434233 and parameters: {'n_estimators': 400, 'max_depth': 6, 'learning_rate': 0.008103086473646576, 'subsample': 0.9312404495902853, 'colsample_bytree': 0.6674921701503564, 'reg_alpha': 0.0010581200388850513, 'reg_lambda': 0.05851423616448627}. Best is trial 24 with value: 0.536921689402406.
[I 2026-06-13 13:06:51,845] Trial 26 finished with value: 0.5352850408595962 and parameters: {'n_estimators': 400, 'max_depth': 8, 'learning_rate': 0.005793403038620832, 'subsample': 0.858996979312172, 'colsample_bytree': 0.5551063794160495, 'reg_alpha': 7.766726729637602e-05, 'reg_lambda': 0.009839814322551075}. Best is trial 24 with value: 0.536921689402406.
[I 2026-06-13 13:06:58,193] Trial 27 finished with value: 0.5290070433530308 and parameters: {'n_estimators': 400, 'max_depth': 8, 'learning_rate': 0.0050685519882752985, 'subsample': 0.8589918761563808, 'colsample_bytree': 0.631116363637954, 'reg_alpha': 0.01144242643974411, 'reg_lambda': 0.010202486008428989}. Best is trial 24 with value: 0.536921689402406.
[I 2026-06-13 13:07:09,634] Trial 28 finished with value: 0.5377114572564676 and parameters: {'n_estimators': 400, 'max_depth': 10, 'learning_rate': 0.006283356727383781, 'subsample': 0.94638073094187, 'colsample_bytree': 0.5473840878761143, 'reg_alpha': 0.00023999673728335077, 'reg_lambda': 0.19317788479673612}. Best is trial 28 with value: 0.5377114572564676.
[I 2026-06-13 13:07:25,986] Trial 29 finished with value: 0.5437672130154458 and parameters: {'n_estimators': 400, 'max_depth': 11, 'learning_rate': 0.006130964706647578, 'subsample': 0.9514869976579342, 'colsample_bytree': 0.551247880420143, 'reg_alpha': 0.00035933480155253246, 'reg_lambda': 0.17474057172056284}. Best is trial 29 with value: 0.5437672130154458.

Best params: {'n_estimators': 400, 'max_depth': 11, 'learning_rate': 0.006130964706647578, 'subsample': 0.9514869976579342, 'colsample_bytree': 0.551247880420143, 'reg_alpha': 0.00035933480155253246, 'reg_lambda': 0.17474057172056284}

[I 2026-06-13 13:07:41,925] A new study created in memory with name: no-name-ec24b14d-b348-401b-8457-e77f185bfd06

Test performance: WAPE=0.0968, R2=0.5438, Bias=-0.4128

============================================================
Training baseline XGBoost for: COPD

[I 2026-06-13 13:07:57,430] Trial 0 finished with value: 0.6289926270713854 and parameters: {'n_estimators': 250, 'max_depth': 12, 'learning_rate': 0.044803926826840625, 'subsample': 0.7993292420985183, 'colsample_bytree': 0.5780093202212182, 'reg_alpha': 1.7699302940633311e-07, 'reg_lambda': 2.9152036385288193e-08}. Best is trial 0 with value: 0.6289926270713854.
[I 2026-06-13 13:08:06,863] Trial 1 finished with value: 0.5508014775009904 and parameters: {'n_estimators': 450, 'max_depth': 9, 'learning_rate': 0.04170553216181044, 'subsample': 0.5102922471479012, 'colsample_bytree': 0.9849549260809971, 'reg_alpha': 0.04566054873446119, 'reg_lambda': 4.997040685255803e-07}. Best is trial 0 with value: 0.6289926270713854.
[I 2026-06-13 13:08:07,317] Trial 2 finished with value: 0.5853264378424028 and parameters: {'n_estimators': 150, 'max_depth': 4, 'learning_rate': 0.012439367209907218, 'subsample': 0.762378215816119, 'colsample_bytree': 0.7159725093210578, 'reg_alpha': 2.1371407316372935e-06, 'reg_lambda': 0.000784915956255507}. Best is trial 0 with value: 0.6289926270713854.
[I 2026-06-13 13:08:08,283] Trial 3 finished with value: 0.5703942930386806 and parameters: {'n_estimators': 150, 'max_depth': 5, 'learning_rate': 0.014983654548550792, 'subsample': 0.728034992108518, 'colsample_bytree': 0.8925879806965068, 'reg_alpha': 3.9572205641009174e-07, 'reg_lambda': 0.00012997969313168238}. Best is trial 0 with value: 0.6289926270713854.
[I 2026-06-13 13:08:10,623] Trial 4 finished with value: 0.5570986302235577 and parameters: {'n_estimators': 350, 'max_depth': 3, 'learning_rate': 0.030860579740535368, 'subsample': 0.5852620618436457, 'colsample_bytree': 0.5325257964926398, 'reg_alpha': 0.39001768308022033, 'reg_lambda': 0.530953226900921}. Best is trial 0 with value: 0.6289926270713854.
[I 2026-06-13 13:08:13,111] Trial 5 finished with value: 0.5786197647379208 and parameters: {'n_estimators': 450, 'max_depth': 6, 'learning_rate': 0.006699530280754897, 'subsample': 0.8421165132560784, 'colsample_bytree': 0.7200762468698007, 'reg_alpha': 9.469038421774442e-08, 'reg_lambda': 9.149877525022172e-05}. Best is trial 0 with value: 0.6289926270713854.
[I 2026-06-13 13:08:21,671] Trial 6 finished with value: 0.5774943240259345 and parameters: {'n_estimators': 100, 'max_depth': 12, 'learning_rate': 0.010855517271883068, 'subsample': 0.831261142176991, 'colsample_bytree': 0.6558555380447055, 'reg_alpha': 0.00014472520367197597, 'reg_lambda': 0.00023641892308789696}. Best is trial 0 with value: 0.6289926270713854.
[I 2026-06-13 13:08:39,523] Trial 7 finished with value: 0.5295123558538898 and parameters: {'n_estimators': 150, 'max_depth': 12, 'learning_rate': 0.05098483969585744, 'subsample': 0.9697494707820946, 'colsample_bytree': 0.9474136752138245, 'reg_alpha': 0.0006070155694141794, 'reg_lambda': 0.23713402899336497}. Best is trial 0 with value: 0.6289926270713854.
[I 2026-06-13 13:08:39,882] Trial 8 finished with value: 0.4266282073366088 and parameters: {'n_estimators': 100, 'max_depth': 4, 'learning_rate': 0.005725482134163321, 'subsample': 0.6626651653816322, 'colsample_bytree': 0.6943386448447411, 'reg_alpha': 1.481809088646707e-06, 'reg_lambda': 0.04264813784432918}. Best is trial 0 with value: 0.6289926270713854.
[I 2026-06-13 13:08:40,921] Trial 9 finished with value: 0.5592593096169004 and parameters: {'n_estimators': 250, 'max_depth': 5, 'learning_rate': 0.025411709798607296, 'subsample': 0.5704621124873813, 'colsample_bytree': 0.9010984903770198, 'reg_alpha': 3.9482545946332394e-08, 'reg_lambda': 0.7854083114461319}. Best is trial 0 with value: 0.6289926270713854.
[I 2026-06-13 13:08:43,610] Trial 10 finished with value: 0.6016506182602122 and parameters: {'n_estimators': 300, 'max_depth': 8, 'learning_rate': 0.09127815799510323, 'subsample': 0.9661451709558936, 'colsample_bytree': 0.5108250728154665, 'reg_alpha': 0.00021259412827992385, 'reg_lambda': 1.3327797860340052e-08}. Best is trial 0 with value: 0.6289926270713854.
[I 2026-06-13 13:08:47,790] Trial 11 finished with value: 0.6085077203967473 and parameters: {'n_estimators': 300, 'max_depth': 9, 'learning_rate': 0.09927334436030408, 'subsample': 0.9968676185612808, 'colsample_bytree': 0.5040206103892897, 'reg_alpha': 4.997544746782185e-05, 'reg_lambda': 1.6936502473309486e-08}. Best is trial 0 with value: 0.6289926270713854.
[I 2026-06-13 13:08:55,131] Trial 12 finished with value: 0.5950533959130807 and parameters: {'n_estimators': 250, 'max_depth': 10, 'learning_rate': 0.09848920654614607, 'subsample': 0.886733279737485, 'colsample_bytree': 0.5920552685676397, 'reg_alpha': 1.261111925404787e-05, 'reg_lambda': 2.5706617512797072e-08}. Best is trial 0 with value: 0.6289926270713854.
[I 2026-06-13 13:09:03,641] Trial 13 finished with value: 0.603274296191034 and parameters: {'n_estimators': 300, 'max_depth': 10, 'learning_rate': 0.06517141496914801, 'subsample': 0.9934311794363789, 'colsample_bytree': 0.5962032728335486, 'reg_alpha': 1.4391960396077776e-08, 'reg_lambda': 6.563146419748597e-07}. Best is trial 0 with value: 0.6289926270713854.
[I 2026-06-13 13:09:06,104] Trial 14 finished with value: 0.5768296153338612 and parameters: {'n_estimators': 350, 'max_depth': 7, 'learning_rate': 0.06408331269580143, 'subsample': 0.8996704994722802, 'colsample_bytree': 0.5859947096170142, 'reg_alpha': 0.002028856958783279, 'reg_lambda': 3.897742686746601e-07}. Best is trial 0 with value: 0.6289926270713854.
[I 2026-06-13 13:09:17,174] Trial 15 finished with value: 0.6321999539351579 and parameters: {'n_estimators': 250, 'max_depth': 11, 'learning_rate': 0.024611984909010988, 'subsample': 0.731057379200564, 'colsample_bytree': 0.5008406069503395, 'reg_alpha': 2.0291436697747434e-05, 'reg_lambda': 3.6440953963738784e-06}. Best is trial 15 with value: 0.6321999539351579.
[I 2026-06-13 13:09:31,407] Trial 16 finished with value: 0.5756932983653765 and parameters: {'n_estimators': 250, 'max_depth': 11, 'learning_rate': 0.02199163418016887, 'subsample': 0.7230473652353425, 'colsample_bytree': 0.7947992509228796, 'reg_alpha': 5.551529837886065e-06, 'reg_lambda': 9.813448460510674e-06}. Best is trial 15 with value: 0.6321999539351579.
[I 2026-06-13 13:09:40,977] Trial 17 finished with value: 0.6131433967820954 and parameters: {'n_estimators': 200, 'max_depth': 11, 'learning_rate': 0.036820989017881396, 'subsample': 0.7935953581257732, 'colsample_bytree': 0.6212239558377118, 'reg_alpha': 0.006415066850629254, 'reg_lambda': 4.023465173414626e-06}. Best is trial 15 with value: 0.6321999539351579.
[I 2026-06-13 13:10:02,577] Trial 18 finished with value: 0.6363098890159746 and parameters: {'n_estimators': 400, 'max_depth': 12, 'learning_rate': 0.01869746510819362, 'subsample': 0.6659414087214435, 'colsample_bytree': 0.5526807122134172, 'reg_alpha': 4.1826614882890194e-07, 'reg_lambda': 7.746697091497292e-08}. Best is trial 18 with value: 0.6363098890159746.
[I 2026-06-13 13:10:22,741] Trial 19 finished with value: 0.6293037802912387 and parameters: {'n_estimators': 500, 'max_depth': 11, 'learning_rate': 0.018155201604055517, 'subsample': 0.6625705475797992, 'colsample_bytree': 0.5328293663190715, 'reg_alpha': 3.081758968811898e-05, 'reg_lambda': 1.4715116479187576e-05}. Best is trial 18 with value: 0.6363098890159746.
[I 2026-06-13 13:10:37,895] Trial 20 finished with value: 0.580975766443007 and parameters: {'n_estimators': 400, 'max_depth': 10, 'learning_rate': 0.009228907348324331, 'subsample': 0.6627207006492868, 'colsample_bytree': 0.7825269757813548, 'reg_alpha': 8.383001016705479e-07, 'reg_lambda': 0.003644969520829825}. Best is trial 18 with value: 0.6363098890159746.
[I 2026-06-13 13:10:58,112] Trial 21 finished with value: 0.6295406363414802 and parameters: {'n_estimators': 500, 'max_depth': 11, 'learning_rate': 0.017737327605414015, 'subsample': 0.6599657009866139, 'colsample_bytree': 0.541432954651889, 'reg_alpha': 1.9315378970717397e-05, 'reg_lambda': 1.6133548583334974e-05}. Best is trial 18 with value: 0.6363098890159746.
[I 2026-06-13 13:11:16,235] Trial 22 finished with value: 0.6218799715539509 and parameters: {'n_estimators': 500, 'max_depth': 11, 'learning_rate': 0.019043256551459234, 'subsample': 0.6107294501742289, 'colsample_bytree': 0.5462724729433261, 'reg_alpha': 1.1422375750790273e-05, 'reg_lambda': 2.2614327516445213e-06}. Best is trial 18 with value: 0.6363098890159746.
[I 2026-06-13 13:11:25,122] Trial 23 finished with value: 0.5924050848825269 and parameters: {'n_estimators': 450, 'max_depth': 9, 'learning_rate': 0.02781115911682786, 'subsample': 0.7035121746323083, 'colsample_bytree': 0.6593712979980784, 'reg_alpha': 3.59449015780105e-06, 'reg_lambda': 2.2052981842572326e-07}. Best is trial 18 with value: 0.6363098890159746.
[I 2026-06-13 13:11:48,547] Trial 24 finished with value: 0.6366039457230039 and parameters: {'n_estimators': 400, 'max_depth': 12, 'learning_rate': 0.015785147007835232, 'subsample': 0.6242933866914708, 'colsample_bytree': 0.5594893058444111, 'reg_alpha': 5.551938177134092e-05, 'reg_lambda': 2.392700352493821e-05}. Best is trial 24 with value: 0.6366039457230039.
[I 2026-06-13 13:12:14,299] Trial 25 finished with value: 0.6293160879697743 and parameters: {'n_estimators': 400, 'max_depth': 12, 'learning_rate': 0.008492460844086485, 'subsample': 0.5307532714102643, 'colsample_bytree': 0.617683261540186, 'reg_alpha': 6.977639794159689e-05, 'reg_lambda': 1.154199446802197e-07}. Best is trial 24 with value: 0.6366039457230039.
[I 2026-06-13 13:12:36,593] Trial 26 finished with value: 0.6407391342907406 and parameters: {'n_estimators': 400, 'max_depth': 12, 'learning_rate': 0.012917608494766199, 'subsample': 0.617483544821809, 'colsample_bytree': 0.5614694810416228, 'reg_alpha': 0.0006617470212260069, 'reg_lambda': 1.8973659915436986e-06}. Best is trial 26 with value: 0.6407391342907406.
[I 2026-06-13 13:13:00,032] Trial 27 finished with value: 0.6193083026835814 and parameters: {'n_estimators': 400, 'max_depth': 12, 'learning_rate': 0.014131281057528002, 'subsample': 0.6098407457136712, 'colsample_bytree': 0.6352387356610217, 'reg_alpha': 0.01144242643974411, 'reg_lambda': 8.11957276005266e-08}. Best is trial 26 with value: 0.6407391342907406.
[I 2026-06-13 13:13:10,349] Trial 28 finished with value: 0.6365119181474928 and parameters: {'n_estimators': 350, 'max_depth': 10, 'learning_rate': 0.010143635469155475, 'subsample': 0.564090587779067, 'colsample_bytree': 0.5638483296723332, 'reg_alpha': 0.0008420202901764686, 'reg_lambda': 3.374569235926194e-05}. Best is trial 26 with value: 0.6407391342907406.
[I 2026-06-13 13:13:20,431] Trial 29 finished with value: 0.6386942769443407 and parameters: {'n_estimators': 350, 'max_depth': 10, 'learning_rate': 0.008938277919152898, 'subsample': 0.5485656473659086, 'colsample_bytree': 0.5707080700053839, 'reg_alpha': 0.0004411609754465425, 'reg_lambda': 3.326226668713737e-05}. Best is trial 26 with value: 0.6407391342907406.

Best params: {'n_estimators': 400, 'max_depth': 12, 'learning_rate': 0.012917608494766199, 'subsample': 0.617483544821809, 'colsample_bytree': 0.5614694810416228, 'reg_alpha': 0.0006617470212260069, 'reg_lambda': 1.8973659915436986e-06}

[I 2026-06-13 13:13:43,426] A new study created in memory with name: no-name-2fd2aaeb-8803-4dae-b9b9-c3ba5de2d752

Test performance: WAPE=0.1150, R2=0.6407, Bias=-0.7776

============================================================
Training baseline XGBoost for: Diabetes

[I 2026-06-13 13:13:57,208] Trial 0 finished with value: 0.6326286291945675 and parameters: {'n_estimators': 250, 'max_depth': 12, 'learning_rate': 0.044803926826840625, 'subsample': 0.7993292420985183, 'colsample_bytree': 0.5780093202212182, 'reg_alpha': 1.7699302940633311e-07, 'reg_lambda': 2.9152036385288193e-08}. Best is trial 0 with value: 0.6326286291945675.
[I 2026-06-13 13:14:08,334] Trial 1 finished with value: 0.6357931554326925 and parameters: {'n_estimators': 450, 'max_depth': 9, 'learning_rate': 0.04170553216181044, 'subsample': 0.5102922471479012, 'colsample_bytree': 0.9849549260809971, 'reg_alpha': 0.04566054873446119, 'reg_lambda': 4.997040685255803e-07}. Best is trial 1 with value: 0.6357931554326925.
[I 2026-06-13 13:14:08,788] Trial 2 finished with value: 0.5893209976112929 and parameters: {'n_estimators': 150, 'max_depth': 4, 'learning_rate': 0.012439367209907218, 'subsample': 0.762378215816119, 'colsample_bytree': 0.7159725093210578, 'reg_alpha': 2.1371407316372935e-06, 'reg_lambda': 0.000784915956255507}. Best is trial 1 with value: 0.6357931554326925.
[I 2026-06-13 13:14:09,494] Trial 3 finished with value: 0.617656010173607 and parameters: {'n_estimators': 150, 'max_depth': 5, 'learning_rate': 0.014983654548550792, 'subsample': 0.728034992108518, 'colsample_bytree': 0.8925879806965068, 'reg_alpha': 3.9572205641009174e-07, 'reg_lambda': 0.00012997969313168238}. Best is trial 1 with value: 0.6357931554326925.
[I 2026-06-13 13:14:10,279] Trial 4 finished with value: 0.6241236948159301 and parameters: {'n_estimators': 350, 'max_depth': 3, 'learning_rate': 0.030860579740535368, 'subsample': 0.5852620618436457, 'colsample_bytree': 0.5325257964926398, 'reg_alpha': 0.39001768308022033, 'reg_lambda': 0.530953226900921}. Best is trial 1 with value: 0.6357931554326925.
[I 2026-06-13 13:14:12,826] Trial 5 finished with value: 0.6319157202457291 and parameters: {'n_estimators': 450, 'max_depth': 6, 'learning_rate': 0.006699530280754897, 'subsample': 0.8421165132560784, 'colsample_bytree': 0.7200762468698007, 'reg_alpha': 9.469038421774442e-08, 'reg_lambda': 9.149877525022172e-05}. Best is trial 1 with value: 0.6357931554326925.
[I 2026-06-13 13:14:21,538] Trial 6 finished with value: 0.536192027661604 and parameters: {'n_estimators': 100, 'max_depth': 12, 'learning_rate': 0.010855517271883068, 'subsample': 0.831261142176991, 'colsample_bytree': 0.6558555380447055, 'reg_alpha': 0.00014472520367197597, 'reg_lambda': 0.00023641892308789696}. Best is trial 1 with value: 0.6357931554326925.
[I 2026-06-13 13:14:35,126] Trial 7 finished with value: 0.6325910808751851 and parameters: {'n_estimators': 150, 'max_depth': 12, 'learning_rate': 0.05098483969585744, 'subsample': 0.9697494707820946, 'colsample_bytree': 0.9474136752138245, 'reg_alpha': 0.0006070155694141794, 'reg_lambda': 0.23713402899336497}. Best is trial 1 with value: 0.6357931554326925.
[I 2026-06-13 13:14:35,450] Trial 8 finished with value: 0.3611362966797562 and parameters: {'n_estimators': 100, 'max_depth': 4, 'learning_rate': 0.005725482134163321, 'subsample': 0.6626651653816322, 'colsample_bytree': 0.6943386448447411, 'reg_alpha': 1.481809088646707e-06, 'reg_lambda': 0.04264813784432918}. Best is trial 1 with value: 0.6357931554326925.
[I 2026-06-13 13:14:36,514] Trial 9 finished with value: 0.6369081848381402 and parameters: {'n_estimators': 250, 'max_depth': 5, 'learning_rate': 0.025411709798607296, 'subsample': 0.5704621124873813, 'colsample_bytree': 0.9010984903770198, 'reg_alpha': 3.9482545946332394e-08, 'reg_lambda': 0.7854083114461319}. Best is trial 9 with value: 0.6369081848381402.
[I 2026-06-13 13:14:40,502] Trial 10 finished with value: 0.6266868817556199 and parameters: {'n_estimators': 300, 'max_depth': 8, 'learning_rate': 0.09127815799510323, 'subsample': 0.9661451709558936, 'colsample_bytree': 0.8360184136122377, 'reg_alpha': 0.00021259412827992385, 'reg_lambda': 1.1572191738342066e-06}. Best is trial 9 with value: 0.6369081848381402.
[I 2026-06-13 13:14:52,477] Trial 11 finished with value: 0.6378757286430259 and parameters: {'n_estimators': 500, 'max_depth': 9, 'learning_rate': 0.02421486565364632, 'subsample': 0.5068048984118391, 'colsample_bytree': 0.9729048599868566, 'reg_alpha': 0.13249079970415722, 'reg_lambda': 1.0514265042794027e-06}. Best is trial 11 with value: 0.6378757286430259.
[I 2026-06-13 13:15:00,797] Trial 12 finished with value: 0.6382823061927578 and parameters: {'n_estimators': 500, 'max_depth': 8, 'learning_rate': 0.02286253504104883, 'subsample': 0.5021426115035387, 'colsample_bytree': 0.8350791350052045, 'reg_alpha': 1.36211131586116e-08, 'reg_lambda': 0.010807045540420099}. Best is trial 12 with value: 0.6382823061927578.
[I 2026-06-13 13:15:11,777] Trial 13 finished with value: 0.6304265609576881 and parameters: {'n_estimators': 500, 'max_depth': 9, 'learning_rate': 0.02201436713743244, 'subsample': 0.507265195242634, 'colsample_bytree': 0.8132777592268099, 'reg_alpha': 0.0068684568185305595, 'reg_lambda': 0.00496389307183381}. Best is trial 12 with value: 0.6382823061927578.
[I 2026-06-13 13:15:18,255] Trial 14 finished with value: 0.6433641438832081 and parameters: {'n_estimators': 500, 'max_depth': 8, 'learning_rate': 0.01786504681965785, 'subsample': 0.60845744956824, 'colsample_bytree': 0.8014472072780106, 'reg_alpha': 1.1519091667110127e-05, 'reg_lambda': 7.9253178660532e-06}. Best is trial 14 with value: 0.6433641438832081.
[I 2026-06-13 13:15:23,455] Trial 15 finished with value: 0.6426799676912716 and parameters: {'n_estimators': 400, 'max_depth': 7, 'learning_rate': 0.01730359321657637, 'subsample': 0.6377971626751088, 'colsample_bytree': 0.8062117293283967, 'reg_alpha': 1.207502917544568e-05, 'reg_lambda': 1.2263147481814412e-05}. Best is trial 14 with value: 0.6433641438832081.
[I 2026-06-13 13:15:26,968] Trial 16 finished with value: 0.6414202439066709 and parameters: {'n_estimators': 400, 'max_depth': 7, 'learning_rate': 0.008777266651425805, 'subsample': 0.6548379037296894, 'colsample_bytree': 0.7897830247330323, 'reg_alpha': 1.3650651371105658e-05, 'reg_lambda': 1.276925019838971e-05}. Best is trial 14 with value: 0.6433641438832081.
[I 2026-06-13 13:15:40,892] Trial 17 finished with value: 0.6411675499333052 and parameters: {'n_estimators': 400, 'max_depth': 10, 'learning_rate': 0.01743173233218364, 'subsample': 0.6531221286499025, 'colsample_bytree': 0.7655874542392869, 'reg_alpha': 1.4906553908137637e-05, 'reg_lambda': 1.9907022408943107e-05}. Best is trial 14 with value: 0.6433641438832081.
[I 2026-06-13 13:15:44,652] Trial 18 finished with value: 0.6424605095075129 and parameters: {'n_estimators': 400, 'max_depth': 7, 'learning_rate': 0.008329615107766735, 'subsample': 0.5915165014252202, 'colsample_bytree': 0.8909361054613245, 'reg_alpha': 1.5303785755916197e-05, 'reg_lambda': 1.2747755202583555e-08}. Best is trial 14 with value: 0.6433641438832081.
[I 2026-06-13 13:15:48,995] Trial 19 finished with value: 0.6376333345049556 and parameters: {'n_estimators': 350, 'max_depth': 7, 'learning_rate': 0.016558310283963543, 'subsample': 0.709351188020094, 'colsample_bytree': 0.653089009195006, 'reg_alpha': 0.002629867626301121, 'reg_lambda': 7.4661735583215055e-06}. Best is trial 14 with value: 0.6433641438832081.
[I 2026-06-13 13:16:03,024] Trial 20 finished with value: 0.627170379214242 and parameters: {'n_estimators': 450, 'max_depth': 10, 'learning_rate': 0.06970063800742968, 'subsample': 0.8979338809467865, 'colsample_bytree': 0.7519979642247641, 'reg_alpha': 5.685519352190053e-05, 'reg_lambda': 1.7535388837813686e-07}. Best is trial 14 with value: 0.6433641438832081.
[I 2026-06-13 13:16:06,811] Trial 21 finished with value: 0.6405142928477474 and parameters: {'n_estimators': 400, 'max_depth': 7, 'learning_rate': 0.008455184012431003, 'subsample': 0.594522356447521, 'colsample_bytree': 0.898748925223184, 'reg_alpha': 1.0856366530180216e-05, 'reg_lambda': 2.091771187039384e-08}. Best is trial 14 with value: 0.6433641438832081.
[I 2026-06-13 13:16:09,011] Trial 22 finished with value: 0.6415237311837243 and parameters: {'n_estimators': 350, 'max_depth': 6, 'learning_rate': 0.01121894518282328, 'subsample': 0.613880664972554, 'colsample_bytree': 0.8544813664339563, 'reg_alpha': 1.8831351715481286e-06, 'reg_lambda': 3.2666739786782534e-06}. Best is trial 14 with value: 0.6433641438832081.
[I 2026-06-13 13:16:17,548] Trial 23 finished with value: 0.6322594424809678 and parameters: {'n_estimators': 450, 'max_depth': 8, 'learning_rate': 0.005057236293953709, 'subsample': 0.5626036690219807, 'colsample_bytree': 0.8717887378779444, 'reg_alpha': 5.887227109015666e-05, 'reg_lambda': 1.2329054743581686e-07}. Best is trial 14 with value: 0.6433641438832081.
[I 2026-06-13 13:16:19,566] Trial 24 finished with value: 0.6276497201583097 and parameters: {'n_estimators': 300, 'max_depth': 6, 'learning_rate': 0.008156082273673747, 'subsample': 0.6932404267187305, 'colsample_bytree': 0.9370758204210594, 'reg_alpha': 8.081742771903794e-06, 'reg_lambda': 3.4527513479223235e-05}. Best is trial 14 with value: 0.6433641438832081.
[I 2026-06-13 13:16:32,698] Trial 25 finished with value: 0.6359357950058321 and parameters: {'n_estimators': 400, 'max_depth': 10, 'learning_rate': 0.030781495621252715, 'subsample': 0.6253294550580107, 'colsample_bytree': 0.7961165498541446, 'reg_alpha': 0.0010973575205170422, 'reg_lambda': 6.66441843220048e-08}. Best is trial 14 with value: 0.6433641438832081.
[I 2026-06-13 13:16:39,189] Trial 26 finished with value: 0.6434929145425952 and parameters: {'n_estimators': 500, 'max_depth': 7, 'learning_rate': 0.012917608494766199, 'subsample': 0.5428369159266988, 'colsample_bytree': 0.9313235884212914, 'reg_alpha': 7.151449050286723e-07, 'reg_lambda': 0.0013311931277702493}. Best is trial 26 with value: 0.6434929145425952.
[I 2026-06-13 13:16:41,340] Trial 27 finished with value: 0.6368525605072765 and parameters: {'n_estimators': 500, 'max_depth': 5, 'learning_rate': 0.013743410668647645, 'subsample': 0.5545551925672456, 'colsample_bytree': 0.9266799578806032, 'reg_alpha': 3.3905722639443705e-07, 'reg_lambda': 0.0011806031580191242}. Best is trial 26 with value: 0.6434929145425952.
[I 2026-06-13 13:16:46,804] Trial 28 finished with value: 0.6372432988436759 and parameters: {'n_estimators': 450, 'max_depth': 8, 'learning_rate': 0.01979021221308455, 'subsample': 0.5469958877599, 'colsample_bytree': 0.760910356035813, 'reg_alpha': 1.1720026184928268e-06, 'reg_lambda': 0.002099080377479368}. Best is trial 26 with value: 0.6434929145425952.
[I 2026-06-13 13:17:07,910] Trial 29 finished with value: 0.6303916507930092 and parameters: {'n_estimators': 500, 'max_depth': 11, 'learning_rate': 0.03193944887456087, 'subsample': 0.7610457516394906, 'colsample_bytree': 0.6473777609029665, 'reg_alpha': 1.6199256944014607e-07, 'reg_lambda': 0.00031618231337759783}. Best is trial 26 with value: 0.6434929145425952.

Best params: {'n_estimators': 500, 'max_depth': 7, 'learning_rate': 0.012917608494766199, 'subsample': 0.5428369159266988, 'colsample_bytree': 0.9313235884212914, 'reg_alpha': 7.151449050286723e-07, 'reg_lambda': 0.0013311931277702493}

[I 2026-06-13 13:17:12,172] A new study created in memory with name: no-name-dda13d24-5f1f-48cf-b765-b01d602a2475

Test performance: WAPE=0.0953, R2=0.6435, Bias=-1.0738

============================================================
Training baseline XGBoost for: Stroke

[I 2026-06-13 13:17:25,681] Trial 0 finished with value: 0.4374917988199899 and parameters: {'n_estimators': 250, 'max_depth': 12, 'learning_rate': 0.044803926826840625, 'subsample': 0.7993292420985183, 'colsample_bytree': 0.5780093202212182, 'reg_alpha': 1.7699302940633311e-07, 'reg_lambda': 2.9152036385288193e-08}. Best is trial 0 with value: 0.4374917988199899.
[I 2026-06-13 13:17:36,574] Trial 1 finished with value: 0.34125842606988666 and parameters: {'n_estimators': 450, 'max_depth': 9, 'learning_rate': 0.04170553216181044, 'subsample': 0.5102922471479012, 'colsample_bytree': 0.9849549260809971, 'reg_alpha': 0.04566054873446119, 'reg_lambda': 4.997040685255803e-07}. Best is trial 0 with value: 0.4374917988199899.
[I 2026-06-13 13:17:37,035] Trial 2 finished with value: 0.46453771032047786 and parameters: {'n_estimators': 150, 'max_depth': 4, 'learning_rate': 0.012439367209907218, 'subsample': 0.762378215816119, 'colsample_bytree': 0.7159725093210578, 'reg_alpha': 2.1371407316372935e-06, 'reg_lambda': 0.000784915956255507}. Best is trial 2 with value: 0.46453771032047786.
[I 2026-06-13 13:17:37,728] Trial 3 finished with value: 0.42213053738948836 and parameters: {'n_estimators': 150, 'max_depth': 5, 'learning_rate': 0.014983654548550792, 'subsample': 0.728034992108518, 'colsample_bytree': 0.8925879806965068, 'reg_alpha': 3.9572205641009174e-07, 'reg_lambda': 0.00012997969313168238}. Best is trial 2 with value: 0.46453771032047786.
[I 2026-06-13 13:17:38,499] Trial 4 finished with value: 0.3732508416944159 and parameters: {'n_estimators': 350, 'max_depth': 3, 'learning_rate': 0.030860579740535368, 'subsample': 0.5852620618436457, 'colsample_bytree': 0.5325257964926398, 'reg_alpha': 0.39001768308022033, 'reg_lambda': 0.530953226900921}. Best is trial 2 with value: 0.46453771032047786.
[I 2026-06-13 13:17:42,876] Trial 5 finished with value: 0.41628246386122747 and parameters: {'n_estimators': 450, 'max_depth': 6, 'learning_rate': 0.006699530280754897, 'subsample': 0.8421165132560784, 'colsample_bytree': 0.7200762468698007, 'reg_alpha': 9.469038421774442e-08, 'reg_lambda': 9.149877525022172e-05}. Best is trial 2 with value: 0.46453771032047786.
[I 2026-06-13 13:17:49,130] Trial 6 finished with value: 0.43988287494947864 and parameters: {'n_estimators': 100, 'max_depth': 12, 'learning_rate': 0.010855517271883068, 'subsample': 0.831261142176991, 'colsample_bytree': 0.6558555380447055, 'reg_alpha': 0.00014472520367197597, 'reg_lambda': 0.00023641892308789696}. Best is trial 2 with value: 0.46453771032047786.
[I 2026-06-13 13:18:01,797] Trial 7 finished with value: 0.3447433609590671 and parameters: {'n_estimators': 150, 'max_depth': 12, 'learning_rate': 0.05098483969585744, 'subsample': 0.9697494707820946, 'colsample_bytree': 0.9474136752138245, 'reg_alpha': 0.0006070155694141794, 'reg_lambda': 0.23713402899336497}. Best is trial 2 with value: 0.46453771032047786.
[I 2026-06-13 13:18:02,132] Trial 8 finished with value: 0.33497906675151545 and parameters: {'n_estimators': 100, 'max_depth': 4, 'learning_rate': 0.005725482134163321, 'subsample': 0.6626651653816322, 'colsample_bytree': 0.6943386448447411, 'reg_alpha': 1.481809088646707e-06, 'reg_lambda': 0.04264813784432918}. Best is trial 2 with value: 0.46453771032047786.
[I 2026-06-13 13:18:03,209] Trial 9 finished with value: 0.3300297526808167 and parameters: {'n_estimators': 250, 'max_depth': 5, 'learning_rate': 0.025411709798607296, 'subsample': 0.5704621124873813, 'colsample_bytree': 0.9010984903770198, 'reg_alpha': 3.9482545946332394e-08, 'reg_lambda': 0.7854083114461319}. Best is trial 2 with value: 0.46453771032047786.
[I 2026-06-13 13:18:10,969] Trial 10 finished with value: 0.33546272874052263 and parameters: {'n_estimators': 500, 'max_depth': 8, 'learning_rate': 0.09127815799510323, 'subsample': 0.9661451709558936, 'colsample_bytree': 0.7978634791402932, 'reg_alpha': 2.4201010269271677e-05, 'reg_lambda': 0.004456706686912844}. Best is trial 2 with value: 0.46453771032047786.
[I 2026-06-13 13:18:12,886] Trial 11 finished with value: 0.4509584691997368 and parameters: {'n_estimators': 100, 'max_depth': 9, 'learning_rate': 0.012971832407724178, 'subsample': 0.844814020142349, 'colsample_bytree': 0.643136340937784, 'reg_alpha': 0.00014291806998728996, 'reg_lambda': 0.00019274987819758896}. Best is trial 2 with value: 0.46453771032047786.
[I 2026-06-13 13:18:17,396] Trial 12 finished with value: 0.4028406682738753 and parameters: {'n_estimators': 200, 'max_depth': 9, 'learning_rate': 0.01437211567663062, 'subsample': 0.8838129988503957, 'colsample_bytree': 0.790918560204845, 'reg_alpha': 1.1870339856511064e-05, 'reg_lambda': 4.8607781462122896e-06}. Best is trial 2 with value: 0.46453771032047786.
[I 2026-06-13 13:18:20,796] Trial 13 finished with value: 0.45997800316423876 and parameters: {'n_estimators': 200, 'max_depth': 7, 'learning_rate': 0.009167593205453134, 'subsample': 0.7134313151821792, 'colsample_bytree': 0.6184338264861576, 'reg_alpha': 0.0013825512603765821, 'reg_lambda': 0.0024598758654156947}. Best is trial 2 with value: 0.46453771032047786.
[I 2026-06-13 13:18:23,062] Trial 14 finished with value: 0.43989862674679325 and parameters: {'n_estimators': 300, 'max_depth': 7, 'learning_rate': 0.008593583026181307, 'subsample': 0.7144064571879521, 'colsample_bytree': 0.5864449217759827, 'reg_alpha': 0.0038002723313209155, 'reg_lambda': 0.004107641823904804}. Best is trial 2 with value: 0.46453771032047786.
[I 2026-06-13 13:18:23,543] Trial 15 finished with value: 0.4117039527253128 and parameters: {'n_estimators': 200, 'max_depth': 3, 'learning_rate': 0.023223713705315806, 'subsample': 0.731057379200564, 'colsample_bytree': 0.7487098945613883, 'reg_alpha': 0.0166606840296547, 'reg_lambda': 0.004543552828853335}. Best is trial 2 with value: 0.46453771032047786.
[I 2026-06-13 13:18:26,255] Trial 16 finished with value: 0.4293644119461357 and parameters: {'n_estimators': 350, 'max_depth': 7, 'learning_rate': 0.00873046059603667, 'subsample': 0.6442183120466017, 'colsample_bytree': 0.6388781173605642, 'reg_alpha': 1.1018012914983747e-08, 'reg_lambda': 9.813448460510674e-06}. Best is trial 2 with value: 0.46453771032047786.
[I 2026-06-13 13:18:27,125] Trial 17 finished with value: 0.38902834011502907 and parameters: {'n_estimators': 200, 'max_depth': 5, 'learning_rate': 0.01894390094321752, 'subsample': 0.7784235516000019, 'colsample_bytree': 0.8211810280697476, 'reg_alpha': 3.622268079665216e-06, 'reg_lambda': 0.041908110047102515}. Best is trial 2 with value: 0.46453771032047786.
[I 2026-06-13 13:18:33,827] Trial 18 finished with value: 0.43169211820575193 and parameters: {'n_estimators': 250, 'max_depth': 10, 'learning_rate': 0.0050929649451137175, 'subsample': 0.6693943125159616, 'colsample_bytree': 0.5005970207840083, 'reg_alpha': 0.3514640625217989, 'reg_lambda': 0.000977822600906809}. Best is trial 2 with value: 0.46453771032047786.
[I 2026-06-13 13:18:35,009] Trial 19 finished with value: 0.4516436345556206 and parameters: {'n_estimators': 150, 'max_depth': 7, 'learning_rate': 0.008296910013337721, 'subsample': 0.8937829425810236, 'colsample_bytree': 0.5879850938313346, 'reg_alpha': 0.0016146212380445143, 'reg_lambda': 3.6535737815373447e-06}. Best is trial 2 with value: 0.46453771032047786.
[I 2026-06-13 13:18:35,883] Trial 20 finished with value: 0.38418656256959305 and parameters: {'n_estimators': 300, 'max_depth': 4, 'learning_rate': 0.018241806866658227, 'subsample': 0.7560730081304023, 'colsample_bytree': 0.6884979853831891, 'reg_alpha': 5.685519352190053e-05, 'reg_lambda': 0.03568938053155346}. Best is trial 2 with value: 0.46453771032047786.
[I 2026-06-13 13:18:37,082] Trial 21 finished with value: 0.45371188186793887 and parameters: {'n_estimators': 150, 'max_depth': 7, 'learning_rate': 0.008861831562232234, 'subsample': 0.9198558692830411, 'colsample_bytree': 0.5904287386708456, 'reg_alpha': 0.0013741834569891127, 'reg_lambda': 1.6133548583334974e-05}. Best is trial 2 with value: 0.46453771032047786.
[I 2026-06-13 13:18:37,885] Trial 22 finished with value: 0.46350944830363294 and parameters: {'n_estimators': 150, 'max_depth': 6, 'learning_rate': 0.010733229869135497, 'subsample': 0.9119518873181452, 'colsample_bytree': 0.6112781995895715, 'reg_alpha': 0.02364751206064328, 'reg_lambda': 2.2507616114196635e-05}. Best is trial 2 with value: 0.46453771032047786.
[I 2026-06-13 13:18:39,087] Trial 23 finished with value: 0.42883330082330207 and parameters: {'n_estimators': 200, 'max_depth': 6, 'learning_rate': 0.011216650869995484, 'subsample': 0.9990239328829952, 'colsample_bytree': 0.7519591800360075, 'reg_alpha': 0.036057102058254936, 'reg_lambda': 0.0011494075987114728}. Best is trial 2 with value: 0.46453771032047786.
[I 2026-06-13 13:18:39,906] Trial 24 finished with value: 0.43517229684085057 and parameters: {'n_estimators': 150, 'max_depth': 6, 'learning_rate': 0.006776564967451529, 'subsample': 0.6870765109418295, 'colsample_bytree': 0.6185762032916613, 'reg_alpha': 0.009442575137054992, 'reg_lambda': 1.3546656519466997e-06}. Best is trial 2 with value: 0.46453771032047786.
[I 2026-06-13 13:18:40,228] Trial 25 finished with value: 0.448140625115228 and parameters: {'n_estimators': 100, 'max_depth': 4, 'learning_rate': 0.011142627749904287, 'subsample': 0.6223974951978786, 'colsample_bytree': 0.5520979573538027, 'reg_alpha': 0.11829250114194434, 'reg_lambda': 3.43183245535556e-05}. Best is trial 2 with value: 0.46453771032047786.
[I 2026-06-13 13:18:42,679] Trial 26 finished with value: 0.3955425502876111 and parameters: {'n_estimators': 200, 'max_depth': 8, 'learning_rate': 0.018890890512728166, 'subsample': 0.807128809372604, 'colsample_bytree': 0.6803222620640018, 'reg_alpha': 0.0003624464121508673, 'reg_lambda': 2.0641878632329591e-07}. Best is trial 2 with value: 0.46453771032047786.
[I 2026-06-13 13:18:45,308] Trial 27 finished with value: 0.46010081807499137 and parameters: {'n_estimators': 250, 'max_depth': 5, 'learning_rate': 0.006905749980465205, 'subsample': 0.9193395999949086, 'colsample_bytree': 0.7368424864528118, 'reg_alpha': 0.004648274417248822, 'reg_lambda': 0.0007388751588740828}. Best is trial 2 with value: 0.46453771032047786.
[I 2026-06-13 13:18:46,687] Trial 28 finished with value: 0.4411634717198918 and parameters: {'n_estimators': 300, 'max_depth': 5, 'learning_rate': 0.0067994053256351175, 'subsample': 0.9298511164779876, 'colsample_bytree': 0.832629678025252, 'reg_alpha': 0.005368642852447296, 'reg_lambda': 0.0005134488719763853}. Best is trial 2 with value: 0.46453771032047786.
[I 2026-06-13 13:18:47,334] Trial 29 finished with value: 0.43322684643507914 and parameters: {'n_estimators': 250, 'max_depth': 3, 'learning_rate': 0.015089040760432432, 'subsample': 0.8762501353621115, 'colsample_bytree': 0.7387073549794463, 'reg_alpha': 0.11405816410650144, 'reg_lambda': 4.616654719981587e-05}. Best is trial 2 with value: 0.46453771032047786.

Best params: {'n_estimators': 150, 'max_depth': 4, 'learning_rate': 0.012439367209907218, 'subsample': 0.762378215816119, 'colsample_bytree': 0.7159725093210578, 'reg_alpha': 2.1371407316372935e-06, 'reg_lambda': 0.000784915956255507}
Test performance: WAPE=0.1167, R2=0.4645, Bias=-0.3888

In [ ]:
baseline_df = pd.DataFrame(baseline_results)
print("\nBaseline XGBoost Summary:")
baseline_df

Baseline XGBoost Summary:

    Disease      WAPE        R2      Bias        Model_Type
0    Cancer  0.185378 -0.482008 -1.418022  Baseline XGBoost
1    Asthma  0.072475 -0.138749 -0.701478  Baseline XGBoost
2       CHD  0.096751  0.543767 -0.412807  Baseline XGBoost
3      COPD  0.115040  0.640739 -0.777643  Baseline XGBoost
4  Diabetes  0.095319  0.643493 -1.073810  Baseline XGBoost
5    Stroke  0.116653  0.464538 -0.388759  Baseline XGBoost

## XGBoost with LLM Embeddings

In [ ]:
features_with_emb = baseline_features + llm_features

In [ ]:
emb_results = []

for target in disease_targets:
    print(f"\n{'='*60}")
    print(f"Training XGBoost + LLM embeddings for: {disease_names[target]}")

    X_train = train_df_emb[features_with_emb]
    y_train = train_df_emb[target]
    X_test = test_df_emb[features_with_emb]
    y_test = test_df_emb[target]

    study = optuna.create_study(direction='maximize', sampler=optuna.samplers.TPESampler(seed=42))
    study.optimize(lambda trial: objective(trial, X_train, y_train, X_test, y_test), n_trials=30, show_progress_bar=False)

    best_params = study.best_params
    print(f"Best params: {best_params}")

    final_model = xgb.XGBRegressor(objective='reg:squarederror', random_state=42, **best_params)
    final_model.fit(X_train, y_train)

    y_pred = final_model.predict(X_test)
    wape = weighted_absolute_percentage_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)
    bias = mean_bias(y_test, y_pred)

    print(f"Test performance: WAPE={wape:.4f}, R2={r2:.4f}, Bias={bias:.4f}")

    emb_results.append({
        'Disease': disease_names[target],
        'WAPE': wape,
        'R2': r2,
        'Bias': bias,
        'Model_Type': 'XGBoost + LLM Emb'
    })

[I 2026-06-13 13:22:52,318] A new study created in memory with name: no-name-004cfc83-4e61-4325-ab9c-76b097cdd721

============================================================
Training XGBoost + LLM embeddings for: Cancer

[I 2026-06-13 13:33:31,196] Trial 0 finished with value: -0.321011196599706 and parameters: {'n_estimators': 250, 'max_depth': 12, 'learning_rate': 0.044803926826840625, 'subsample': 0.7993292420985183, 'colsample_bytree': 0.5780093202212182, 'reg_alpha': 1.7699302940633311e-07, 'reg_lambda': 2.9152036385288193e-08}. Best is trial 0 with value: -0.321011196599706.
[I 2026-06-13 13:40:39,102] Trial 1 finished with value: -0.3675264216748755 and parameters: {'n_estimators': 450, 'max_depth': 9, 'learning_rate': 0.04170553216181044, 'subsample': 0.5102922471479012, 'colsample_bytree': 0.9849549260809971, 'reg_alpha': 0.04566054873446119, 'reg_lambda': 4.997040685255803e-07}. Best is trial 0 with value: -0.321011196599706.
[I 2026-06-13 13:40:53,703] Trial 2 finished with value: -0.5275108807264259 and parameters: {'n_estimators': 150, 'max_depth': 4, 'learning_rate': 0.012439367209907218, 'subsample': 0.762378215816119, 'colsample_bytree': 0.7159725093210578, 'reg_alpha': 2.1371407316372935e-06, 'reg_lambda': 0.000784915956255507}. Best is trial 0 with value: -0.321011196599706.
[I 2026-06-13 13:41:17,287] Trial 3 finished with value: -0.5285779475057613 and parameters: {'n_estimators': 150, 'max_depth': 5, 'learning_rate': 0.014983654548550792, 'subsample': 0.728034992108518, 'colsample_bytree': 0.8925879806965068, 'reg_alpha': 3.9572205641009174e-07, 'reg_lambda': 0.00012997969313168238}. Best is trial 0 with value: -0.321011196599706.
[I 2026-06-13 13:41:40,703] Trial 4 finished with value: -0.5643246023564545 and parameters: {'n_estimators': 350, 'max_depth': 3, 'learning_rate': 0.030860579740535368, 'subsample': 0.5852620618436457, 'colsample_bytree': 0.5325257964926398, 'reg_alpha': 0.39001768308022033, 'reg_lambda': 0.530953226900921}. Best is trial 0 with value: -0.321011196599706.
[I 2026-06-13 13:43:14,503] Trial 5 finished with value: -0.49696304861432083 and parameters: {'n_estimators': 450, 'max_depth': 6, 'learning_rate': 0.006699530280754897, 'subsample': 0.8421165132560784, 'colsample_bytree': 0.7200762468698007, 'reg_alpha': 9.469038421774442e-08, 'reg_lambda': 9.149877525022172e-05}. Best is trial 0 with value: -0.321011196599706.
[I 2026-06-13 13:47:50,104] Trial 6 finished with value: -0.4002612112642425 and parameters: {'n_estimators': 100, 'max_depth': 12, 'learning_rate': 0.010855517271883068, 'subsample': 0.831261142176991, 'colsample_bytree': 0.6558555380447055, 'reg_alpha': 0.00014472520367197597, 'reg_lambda': 0.00023641892308789696}. Best is trial 0 with value: -0.321011196599706.
[I 2026-06-13 13:55:55,082] Trial 7 finished with value: -0.4152766031456909 and parameters: {'n_estimators': 150, 'max_depth': 12, 'learning_rate': 0.05098483969585744, 'subsample': 0.9697494707820946, 'colsample_bytree': 0.9474136752138245, 'reg_alpha': 0.0006070155694141794, 'reg_lambda': 0.23713402899336497}. Best is trial 0 with value: -0.321011196599706.
[I 2026-06-13 13:56:05,577] Trial 8 finished with value: -0.5308948411692966 and parameters: {'n_estimators': 100, 'max_depth': 4, 'learning_rate': 0.005725482134163321, 'subsample': 0.6626651653816322, 'colsample_bytree': 0.6943386448447411, 'reg_alpha': 1.481809088646707e-06, 'reg_lambda': 0.04264813784432918}. Best is trial 0 with value: -0.321011196599706.
[I 2026-06-13 13:56:43,209] Trial 9 finished with value: -0.5207129090371223 and parameters: {'n_estimators': 250, 'max_depth': 5, 'learning_rate': 0.025411709798607296, 'subsample': 0.5704621124873813, 'colsample_bytree': 0.9010984903770198, 'reg_alpha': 3.9482545946332394e-08, 'reg_lambda': 0.7854083114461319}. Best is trial 0 with value: -0.321011196599706.
[I 2026-06-13 13:58:51,546] Trial 10 finished with value: -0.30707529519408494 and parameters: {'n_estimators': 300, 'max_depth': 8, 'learning_rate': 0.09127815799510323, 'subsample': 0.9661451709558936, 'colsample_bytree': 0.5108250728154665, 'reg_alpha': 0.00021259412827992385, 'reg_lambda': 1.3327797860340052e-08}. Best is trial 10 with value: -0.30707529519408494.
[I 2026-06-13 14:02:05,927] Trial 11 finished with value: -0.31598675484087524 and parameters: {'n_estimators': 300, 'max_depth': 9, 'learning_rate': 0.09927334436030408, 'subsample': 0.9968676185612808, 'colsample_bytree': 0.5040206103892897, 'reg_alpha': 4.997544746782185e-05, 'reg_lambda': 1.6936502473309486e-08}. Best is trial 10 with value: -0.30707529519408494.
[I 2026-06-13 14:04:07,616] Trial 12 finished with value: -0.31016262356208313 and parameters: {'n_estimators': 300, 'max_depth': 8, 'learning_rate': 0.0985763691245156, 'subsample': 0.9995004182654049, 'colsample_bytree': 0.5021839605740446, 'reg_alpha': 0.00012824107714249285, 'reg_lambda': 2.2940865711863698e-08}. Best is trial 10 with value: -0.30707529519408494.
[I 2026-06-13 14:06:51,157] Trial 13 finished with value: -0.2997453850977998 and parameters: {'n_estimators': 350, 'max_depth': 8, 'learning_rate': 0.08808382764055064, 'subsample': 0.926899016684177, 'colsample_bytree': 0.6161099984015154, 'reg_alpha': 0.0016396392974934574, 'reg_lambda': 6.563146419748597e-07}. Best is trial 13 with value: -0.2997453850977998.
[I 2026-06-13 14:08:48,799] Trial 14 finished with value: -0.30788067520992124 and parameters: {'n_estimators': 400, 'max_depth': 7, 'learning_rate': 0.06808977293310314, 'subsample': 0.9080178078055495, 'colsample_bytree': 0.6116112381976404, 'reg_alpha': 0.005214644332305004, 'reg_lambda': 7.461544217853947e-07}. Best is trial 13 with value: -0.2997453850977998.
[I 2026-06-13 14:17:23,430] Trial 15 finished with value: -0.3206385552054105 and parameters: {'n_estimators': 500, 'max_depth': 10, 'learning_rate': 0.06932714625065078, 'subsample': 0.9040330172235821, 'colsample_bytree': 0.5979644942759227, 'reg_alpha': 0.002961742478975068, 'reg_lambda': 1.1615134174157575e-06}. Best is trial 13 with value: -0.2997453850977998.
[I 2026-06-13 14:25:27,057] Trial 16 finished with value: -0.4074697771907274 and parameters: {'n_estimators': 350, 'max_depth': 10, 'learning_rate': 0.07398745091915376, 'subsample': 0.9117484725634621, 'colsample_bytree': 0.7897830247330323, 'reg_alpha': 1.7665186876172412e-05, 'reg_lambda': 9.813448460510674e-06}. Best is trial 13 with value: -0.2997453850977998.
[I 2026-06-13 14:26:56,403] Trial 17 finished with value: -0.4262506622163882 and parameters: {'n_estimators': 250, 'max_depth': 7, 'learning_rate': 0.029306469861307624, 'subsample': 0.9343464640884938, 'colsample_bytree': 0.7912554411220167, 'reg_alpha': 0.01370133743109876, 'reg_lambda': 1.4138414487999646e-07}. Best is trial 13 with value: -0.2997453850977998.
[I 2026-06-13 14:29:37,273] Trial 18 finished with value: -0.3145737558134645 and parameters: {'n_estimators': 350, 'max_depth': 8, 'learning_rate': 0.057312662854406865, 'subsample': 0.8622335346819526, 'colsample_bytree': 0.5636641861101147, 'reg_alpha': 0.17915781043428247, 'reg_lambda': 7.364144103857295e-06}. Best is trial 13 with value: -0.2997453850977998.
[I 2026-06-13 14:31:36,387] Trial 19 finished with value: -0.31307138275324453 and parameters: {'n_estimators': 400, 'max_depth': 7, 'learning_rate': 0.0834535382185945, 'subsample': 0.951726283899732, 'colsample_bytree': 0.6327808934984145, 'reg_alpha': 0.0013892469267470207, 'reg_lambda': 1.0915230441496749e-07}. Best is trial 13 with value: -0.2997453850977998.
[I 2026-06-13 14:36:01,166] Trial 20 finished with value: -0.3767747648773627 and parameters: {'n_estimators': 200, 'max_depth': 10, 'learning_rate': 0.021428941200141494, 'subsample': 0.8674149529132084, 'colsample_bytree': 0.6671876770805228, 'reg_alpha': 9.915137268367448e-06, 'reg_lambda': 4.36698294332618e-06}. Best is trial 13 with value: -0.2997453850977998.
[I 2026-06-13 14:37:57,607] Trial 21 finished with value: -0.3083542609421277 and parameters: {'n_estimators': 400, 'max_depth': 7, 'learning_rate': 0.06867003956157823, 'subsample': 0.8978380195932983, 'colsample_bytree': 0.6055993599699274, 'reg_alpha': 0.00533491801724853, 'reg_lambda': 5.287696877569462e-07}. Best is trial 13 with value: -0.2997453850977998.
[I 2026-06-13 14:40:54,545] Trial 22 finished with value: -0.32158855321975643 and parameters: {'n_estimators': 400, 'max_depth': 8, 'learning_rate': 0.05845497179648933, 'subsample': 0.9506566423699602, 'colsample_bytree': 0.5511432740542206, 'reg_alpha': 0.000581373158073984, 'reg_lambda': 1.1914628539833783e-07}. Best is trial 13 with value: -0.2997453850977998.
[I 2026-06-13 14:41:50,612] Trial 23 finished with value: -0.40910078606787037 and parameters: {'n_estimators': 300, 'max_depth': 6, 'learning_rate': 0.03761190226789709, 'subsample': 0.888898373653854, 'colsample_bytree': 0.6204841431345296, 'reg_alpha': 0.02780892639478523, 'reg_lambda': 1.6737130361946293e-06}. Best is trial 13 with value: -0.2997453850977998.
[I 2026-06-13 14:48:15,915] Trial 24 finished with value: -0.3806158427716968 and parameters: {'n_estimators': 450, 'max_depth': 9, 'learning_rate': 0.08420159291702603, 'subsample': 0.8025939130993532, 'colsample_bytree': 0.7543307446342641, 'reg_alpha': 0.00031806146239158543, 'reg_lambda': 1.1711196307773993e-05}. Best is trial 13 with value: -0.2997453850977998.
[I 2026-06-13 14:49:17,755] Trial 25 finished with value: -0.3660795008140916 and parameters: {'n_estimators': 350, 'max_depth': 6, 'learning_rate': 0.05994230128522237, 'subsample': 0.9312404495902853, 'colsample_bytree': 0.546368123663256, 'reg_alpha': 0.08666509251557214, 'reg_lambda': 1.341210345072139e-07}. Best is trial 13 with value: -0.2997453850977998.
[I 2026-06-13 14:53:11,163] Trial 26 finished with value: -0.3302065424380518 and parameters: {'n_estimators': 500, 'max_depth': 8, 'learning_rate': 0.08148117029142155, 'subsample': 0.9863297779085375, 'colsample_bytree': 0.653846888231739, 'reg_alpha': 0.006635909115717231, 'reg_lambda': 4.628857265112495e-08}. Best is trial 13 with value: -0.2997453850977998.
[I 2026-06-13 15:01:48,971] Trial 27 finished with value: -0.3188995808872499 and parameters: {'n_estimators': 300, 'max_depth': 11, 'learning_rate': 0.04586922800610183, 'subsample': 0.813300150959628, 'colsample_bytree': 0.5923682122460847, 'reg_alpha': 0.0011945680262294635, 'reg_lambda': 0.004490848178655965}. Best is trial 13 with value: -0.2997453850977998.
[I 2026-06-13 15:03:39,242] Trial 28 finished with value: -0.35065746484595883 and parameters: {'n_estimators': 400, 'max_depth': 7, 'learning_rate': 0.03688203502559327, 'subsample': 0.8717660581075367, 'colsample_bytree': 0.5285661283741939, 'reg_alpha': 2.4021881935714054e-05, 'reg_lambda': 3.312610711163917e-05}. Best is trial 13 with value: -0.2997453850977998.
[I 2026-06-13 15:06:40,343] Trial 29 finished with value: -0.30412507818086065 and parameters: {'n_estimators': 250, 'max_depth': 9, 'learning_rate': 0.09987752563516382, 'subsample': 0.7712451359796146, 'colsample_bytree': 0.5783679762544055, 'reg_alpha': 0.00010781182788714702, 'reg_lambda': 4.789595462347144e-07}. Best is trial 13 with value: -0.2997453850977998.

Best params: {'n_estimators': 350, 'max_depth': 8, 'learning_rate': 0.08808382764055064, 'subsample': 0.926899016684177, 'colsample_bytree': 0.6161099984015154, 'reg_alpha': 0.0016396392974934574, 'reg_lambda': 6.563146419748597e-07}

[I 2026-06-13 15:09:15,912] A new study created in memory with name: no-name-0947a3f7-5447-471c-9c5f-06ca19b327c5

Test performance: WAPE=0.1793, R2=-0.2997, Bias=-1.5464

============================================================
Training XGBoost + LLM embeddings for: Asthma

[I 2026-06-13 15:21:23,744] Trial 0 finished with value: -0.05388106414773364 and parameters: {'n_estimators': 250, 'max_depth': 12, 'learning_rate': 0.044803926826840625, 'subsample': 0.7993292420985183, 'colsample_bytree': 0.5780093202212182, 'reg_alpha': 1.7699302940633311e-07, 'reg_lambda': 2.9152036385288193e-08}. Best is trial 0 with value: -0.05388106414773364.
[I 2026-06-13 15:29:07,774] Trial 1 finished with value: -0.03734742486264153 and parameters: {'n_estimators': 450, 'max_depth': 9, 'learning_rate': 0.04170553216181044, 'subsample': 0.5102922471479012, 'colsample_bytree': 0.9849549260809971, 'reg_alpha': 0.04566054873446119, 'reg_lambda': 4.997040685255803e-07}. Best is trial 1 with value: -0.03734742486264153.
[I 2026-06-13 15:29:23,505] Trial 2 finished with value: -0.40000285456461837 and parameters: {'n_estimators': 150, 'max_depth': 4, 'learning_rate': 0.012439367209907218, 'subsample': 0.762378215816119, 'colsample_bytree': 0.7159725093210578, 'reg_alpha': 2.1371407316372935e-06, 'reg_lambda': 0.000784915956255507}. Best is trial 1 with value: -0.03734742486264153.
[I 2026-06-13 15:29:48,365] Trial 3 finished with value: -0.30325255324839695 and parameters: {'n_estimators': 150, 'max_depth': 5, 'learning_rate': 0.014983654548550792, 'subsample': 0.728034992108518, 'colsample_bytree': 0.8925879806965068, 'reg_alpha': 3.9572205641009174e-07, 'reg_lambda': 0.00012997969313168238}. Best is trial 1 with value: -0.03734742486264153.
[I 2026-06-13 15:30:12,342] Trial 4 finished with value: -0.2293879067736797 and parameters: {'n_estimators': 350, 'max_depth': 3, 'learning_rate': 0.030860579740535368, 'subsample': 0.5852620618436457, 'colsample_bytree': 0.5325257964926398, 'reg_alpha': 0.39001768308022033, 'reg_lambda': 0.530953226900921}. Best is trial 1 with value: -0.03734742486264153.
[I 2026-06-13 15:31:59,627] Trial 5 finished with value: -0.1910855433974603 and parameters: {'n_estimators': 450, 'max_depth': 6, 'learning_rate': 0.006699530280754897, 'subsample': 0.8421165132560784, 'colsample_bytree': 0.7200762468698007, 'reg_alpha': 9.469038421774442e-08, 'reg_lambda': 9.149877525022172e-05}. Best is trial 1 with value: -0.03734742486264153.
[I 2026-06-13 15:38:00,236] Trial 6 finished with value: -0.172107155456388 and parameters: {'n_estimators': 100, 'max_depth': 12, 'learning_rate': 0.010855517271883068, 'subsample': 0.831261142176991, 'colsample_bytree': 0.6558555380447055, 'reg_alpha': 0.00014472520367197597, 'reg_lambda': 0.00023641892308789696}. Best is trial 1 with value: -0.03734742486264153.
[I 2026-06-13 15:48:52,500] Trial 7 finished with value: -0.11083095772428586 and parameters: {'n_estimators': 150, 'max_depth': 12, 'learning_rate': 0.05098483969585744, 'subsample': 0.9697494707820946, 'colsample_bytree': 0.9474136752138245, 'reg_alpha': 0.0006070155694141794, 'reg_lambda': 0.23713402899336497}. Best is trial 1 with value: -0.03734742486264153.
[I 2026-06-13 15:49:03,483] Trial 8 finished with value: -0.45993660542178927 and parameters: {'n_estimators': 100, 'max_depth': 4, 'learning_rate': 0.005725482134163321, 'subsample': 0.6626651653816322, 'colsample_bytree': 0.6943386448447411, 'reg_alpha': 1.481809088646707e-06, 'reg_lambda': 0.04264813784432918}. Best is trial 1 with value: -0.03734742486264153.
[I 2026-06-13 15:49:43,164] Trial 9 finished with value: -0.17875479966447494 and parameters: {'n_estimators': 250, 'max_depth': 5, 'learning_rate': 0.025411709798607296, 'subsample': 0.5704621124873813, 'colsample_bytree': 0.9010984903770198, 'reg_alpha': 3.9482545946332394e-08, 'reg_lambda': 0.7854083114461319}. Best is trial 1 with value: -0.03734742486264153.
[I 2026-06-13 15:56:10,298] Trial 10 finished with value: -0.030645101368915295 and parameters: {'n_estimators': 500, 'max_depth': 9, 'learning_rate': 0.09127815799510323, 'subsample': 0.5089809378074098, 'colsample_bytree': 0.8146364282649428, 'reg_alpha': 0.182523321053656, 'reg_lambda': 1.3327797860340052e-08}. Best is trial 10 with value: -0.030645101368915295.
[I 2026-06-13 16:01:45,190] Trial 11 finished with value: -0.05240160783594483 and parameters: {'n_estimators': 500, 'max_depth': 9, 'learning_rate': 0.09924359931377322, 'subsample': 0.5043736834843053, 'colsample_bytree': 0.8238808223534149, 'reg_alpha': 0.5400440497088494, 'reg_lambda': 1.6936502473309486e-08}. Best is trial 10 with value: -0.030645101368915295.
[I 2026-06-13 16:07:38,403] Trial 12 finished with value: -0.06265321470356633 and parameters: {'n_estimators': 400, 'max_depth': 9, 'learning_rate': 0.09837824977261485, 'subsample': 0.5021731139239561, 'colsample_bytree': 0.8047967622120994, 'reg_alpha': 0.02484280910211506, 'reg_lambda': 9.474668849034313e-07}. Best is trial 10 with value: -0.030645101368915295.
[I 2026-06-13 16:16:31,132] Trial 13 finished with value: -0.06166320433872019 and parameters: {'n_estimators': 500, 'max_depth': 9, 'learning_rate': 0.06379665685193586, 'subsample': 0.6051232104224304, 'colsample_bytree': 0.9900586663895835, 'reg_alpha': 0.00887522688320591, 'reg_lambda': 6.563146419748597e-07}. Best is trial 10 with value: -0.030645101368915295.
[I 2026-06-13 16:18:53,370] Trial 14 finished with value: -0.05700424366035528 and parameters: {'n_estimators': 400, 'max_depth': 7, 'learning_rate': 0.030572176449909175, 'subsample': 0.6399954876351523, 'colsample_bytree': 0.8095839387020464, 'reg_alpha': 0.028477687860762407, 'reg_lambda': 5.494869182293743e-07}. Best is trial 10 with value: -0.030645101368915295.
[I 2026-06-13 16:30:41,417] Trial 15 finished with value: -0.05710868968321958 and parameters: {'n_estimators': 450, 'max_depth': 10, 'learning_rate': 0.06905000417296209, 'subsample': 0.5421707987275746, 'colsample_bytree': 0.9980084946806067, 'reg_alpha': 0.0011185998282529164, 'reg_lambda': 3.1816848577868745e-06}. Best is trial 10 with value: -0.030645101368915295.
[I 2026-06-13 16:33:05,914] Trial 16 finished with value: -0.06575227377518811 and parameters: {'n_estimators': 350, 'max_depth': 7, 'learning_rate': 0.020581406199238504, 'subsample': 0.6897796683137567, 'colsample_bytree': 0.8933139358849993, 'reg_alpha': 3.061902905963988e-05, 'reg_lambda': 9.05564937846756e-08}. Best is trial 10 with value: -0.030645101368915295.
[I 2026-06-13 16:43:52,696] Trial 17 finished with value: -0.038258200715892476 and parameters: {'n_estimators': 500, 'max_depth': 10, 'learning_rate': 0.0413763496808004, 'subsample': 0.5350942371288058, 'colsample_bytree': 0.773710225439044, 'reg_alpha': 0.13132385924648426, 'reg_lambda': 2.0396622586768678e-05}. Best is trial 10 with value: -0.030645101368915295.
[I 2026-06-13 16:48:27,045] Trial 18 finished with value: -0.03413753820699594 and parameters: {'n_estimators': 450, 'max_depth': 8, 'learning_rate': 0.06202033435969815, 'subsample': 0.6077152746957687, 'colsample_bytree': 0.8576874196402302, 'reg_alpha': 0.004545229623549694, 'reg_lambda': 1.264621061352578e-07}. Best is trial 10 with value: -0.030645101368915295.
[I 2026-06-13 16:50:44,665] Trial 19 finished with value: -0.026247343382715504 and parameters: {'n_estimators': 350, 'max_depth': 7, 'learning_rate': 0.08152515586890059, 'subsample': 0.6227492831867513, 'colsample_bytree': 0.861490742454545, 'reg_alpha': 0.00417212452789899, 'reg_lambda': 1.0915230441496749e-07}. Best is trial 19 with value: -0.026247343382715504.
[I 2026-06-13 16:52:14,071] Trial 20 finished with value: -0.05477324678285789 and parameters: {'n_estimators': 250, 'max_depth': 7, 'learning_rate': 0.07964892513737651, 'subsample': 0.9826162589395974, 'colsample_bytree': 0.7631560621637522, 'reg_alpha': 2.8971093613025048e-05, 'reg_lambda': 1.1910934588339993e-08}. Best is trial 19 with value: -0.026247343382715504.
[I 2026-06-13 16:55:49,791] Trial 21 finished with value: -0.04287393850202492 and parameters: {'n_estimators': 350, 'max_depth': 8, 'learning_rate': 0.059786671565438154, 'subsample': 0.6259683216930333, 'colsample_bytree': 0.8587574978128981, 'reg_alpha': 0.004098293721656967, 'reg_lambda': 9.565814805986505e-08}. Best is trial 19 with value: -0.026247343382715504.
[I 2026-06-13 16:59:56,125] Trial 22 finished with value: -0.04998220186114222 and parameters: {'n_estimators': 400, 'max_depth': 8, 'learning_rate': 0.08646830321472297, 'subsample': 0.6820387687293453, 'colsample_bytree': 0.8705473702779336, 'reg_alpha': 0.00238257337487772, 'reg_lambda': 8.184137811115659e-08}. Best is trial 19 with value: -0.026247343382715504.
[I 2026-06-13 17:07:21,785] Trial 23 finished with value: -0.04205633998357361 and parameters: {'n_estimators': 300, 'max_depth': 10, 'learning_rate': 0.05700133763204504, 'subsample': 0.5817883299809574, 'colsample_bytree': 0.8340973375644583, 'reg_alpha': 0.00029204814001051533, 'reg_lambda': 7.942389779577405e-06}. Best is trial 19 with value: -0.026247343382715504.
[I 2026-06-13 17:12:33,738] Trial 24 finished with value: -0.047517606128700374 and parameters: {'n_estimators': 450, 'max_depth': 8, 'learning_rate': 0.07385394842354971, 'subsample': 0.6242933866914708, 'colsample_bytree': 0.9370758204210594, 'reg_alpha': 0.11408008436218121, 'reg_lambda': 1.578985981737852e-07}. Best is trial 19 with value: -0.026247343382715504.
[I 2026-06-13 17:14:25,628] Trial 25 finished with value: -0.050234134469396174 and parameters: {'n_estimators': 500, 'max_depth': 6, 'learning_rate': 0.03700765794366925, 'subsample': 0.5509328874979031, 'colsample_bytree': 0.7686114303305063, 'reg_alpha': 0.9916233873773795, 'reg_lambda': 4.139091270917636e-06}. Best is trial 19 with value: -0.026247343382715504.
[I 2026-06-13 17:26:37,130] Trial 26 finished with value: -0.08111646924071803 and parameters: {'n_estimators': 300, 'max_depth': 11, 'learning_rate': 0.05303358015633104, 'subsample': 0.7277007208010557, 'colsample_bytree': 0.9351219987006539, 'reg_alpha': 0.006635909115717231, 'reg_lambda': 3.6608941226154136e-08}. Best is trial 19 with value: -0.026247343382715504.
[I 2026-06-13 17:28:09,721] Trial 27 finished with value: -0.06308917696173233 and parameters: {'n_estimators': 400, 'max_depth': 6, 'learning_rate': 0.07748736640406599, 'subsample': 0.5985861243736631, 'colsample_bytree': 0.8555603516386662, 'reg_alpha': 7.467050263978142e-05, 'reg_lambda': 2.4146637605533496e-07}. Best is trial 19 with value: -0.026247343382715504.
[I 2026-06-13 17:31:56,443] Trial 28 finished with value: -0.023905025898972143 and parameters: {'n_estimators': 450, 'max_depth': 8, 'learning_rate': 0.0667828782256309, 'subsample': 0.6546229685403953, 'colsample_bytree': 0.6549162921667234, 'reg_alpha': 0.009021816413275647, 'reg_lambda': 1.8545513926846121e-06}. Best is trial 28 with value: -0.023905025898972143.
[I 2026-06-13 17:38:20,733] Trial 29 finished with value: -0.06910740456576492 and parameters: {'n_estimators': 350, 'max_depth': 11, 'learning_rate': 0.09987752563516382, 'subsample': 0.7142493238579058, 'colsample_bytree': 0.6277411073715813, 'reg_alpha': 0.12512929956640986, 'reg_lambda': 1.8807335039950064e-06}. Best is trial 28 with value: -0.023905025898972143.

Best params: {'n_estimators': 450, 'max_depth': 8, 'learning_rate': 0.0667828782256309, 'subsample': 0.6546229685403953, 'colsample_bytree': 0.6549162921667234, 'reg_alpha': 0.009021816413275647, 'reg_lambda': 1.8545513926846121e-06}

[I 2026-06-13 17:41:56,369] A new study created in memory with name: no-name-20e96fe5-7d06-43f5-af7a-26a3b248e394

Test performance: WAPE=0.0737, R2=-0.0239, Bias=-0.7443

============================================================
Training XGBoost + LLM embeddings for: CHD

[I 2026-06-13 17:53:55,608] Trial 0 finished with value: 0.6282907557601989 and parameters: {'n_estimators': 250, 'max_depth': 12, 'learning_rate': 0.044803926826840625, 'subsample': 0.7993292420985183, 'colsample_bytree': 0.5780093202212182, 'reg_alpha': 1.7699302940633311e-07, 'reg_lambda': 2.9152036385288193e-08}. Best is trial 0 with value: 0.6282907557601989.
[I 2026-06-13 18:01:38,410] Trial 1 finished with value: 0.5477518972487511 and parameters: {'n_estimators': 450, 'max_depth': 9, 'learning_rate': 0.04170553216181044, 'subsample': 0.5102922471479012, 'colsample_bytree': 0.9849549260809971, 'reg_alpha': 0.04566054873446119, 'reg_lambda': 4.997040685255803e-07}. Best is trial 0 with value: 0.6282907557601989.
[I 2026-06-13 18:01:54,724] Trial 2 finished with value: 0.5241437208678987 and parameters: {'n_estimators': 150, 'max_depth': 4, 'learning_rate': 0.012439367209907218, 'subsample': 0.762378215816119, 'colsample_bytree': 0.7159725093210578, 'reg_alpha': 2.1371407316372935e-06, 'reg_lambda': 0.000784915956255507}. Best is trial 0 with value: 0.6282907557601989.
[I 2026-06-13 18:02:20,320] Trial 3 finished with value: 0.5255117689941031 and parameters: {'n_estimators': 150, 'max_depth': 5, 'learning_rate': 0.014983654548550792, 'subsample': 0.728034992108518, 'colsample_bytree': 0.8925879806965068, 'reg_alpha': 3.9572205641009174e-07, 'reg_lambda': 0.00012997969313168238}. Best is trial 0 with value: 0.6282907557601989.
[I 2026-06-13 18:02:45,217] Trial 4 finished with value: 0.5219011368747547 and parameters: {'n_estimators': 350, 'max_depth': 3, 'learning_rate': 0.030860579740535368, 'subsample': 0.5852620618436457, 'colsample_bytree': 0.5325257964926398, 'reg_alpha': 0.39001768308022033, 'reg_lambda': 0.530953226900921}. Best is trial 0 with value: 0.6282907557601989.
[I 2026-06-13 18:04:33,169] Trial 5 finished with value: 0.5365477467155277 and parameters: {'n_estimators': 450, 'max_depth': 6, 'learning_rate': 0.006699530280754897, 'subsample': 0.8421165132560784, 'colsample_bytree': 0.7200762468698007, 'reg_alpha': 9.469038421774442e-08, 'reg_lambda': 9.149877525022172e-05}. Best is trial 0 with value: 0.6282907557601989.
[I 2026-06-13 18:10:30,507] Trial 6 finished with value: 0.5464224511245628 and parameters: {'n_estimators': 100, 'max_depth': 12, 'learning_rate': 0.010855517271883068, 'subsample': 0.831261142176991, 'colsample_bytree': 0.6558555380447055, 'reg_alpha': 0.00014472520367197597, 'reg_lambda': 0.00023641892308789696}. Best is trial 0 with value: 0.6282907557601989.
[I 2026-06-13 18:21:03,139] Trial 7 finished with value: 0.5349368804913879 and parameters: {'n_estimators': 150, 'max_depth': 12, 'learning_rate': 0.05098483969585744, 'subsample': 0.9697494707820946, 'colsample_bytree': 0.9474136752138245, 'reg_alpha': 0.0006070155694141794, 'reg_lambda': 0.23713402899336497}. Best is trial 0 with value: 0.6282907557601989.
[I 2026-06-13 18:21:14,625] Trial 8 finished with value: 0.36161010460937015 and parameters: {'n_estimators': 100, 'max_depth': 4, 'learning_rate': 0.005725482134163321, 'subsample': 0.6626651653816322, 'colsample_bytree': 0.6943386448447411, 'reg_alpha': 1.481809088646707e-06, 'reg_lambda': 0.04264813784432918}. Best is trial 0 with value: 0.6282907557601989.
[I 2026-06-13 18:21:54,011] Trial 9 finished with value: 0.501440456076226 and parameters: {'n_estimators': 250, 'max_depth': 5, 'learning_rate': 0.025411709798607296, 'subsample': 0.5704621124873813, 'colsample_bytree': 0.9010984903770198, 'reg_alpha': 3.9482545946332394e-08, 'reg_lambda': 0.7854083114461319}. Best is trial 0 with value: 0.6282907557601989.
[I 2026-06-13 18:24:04,942] Trial 10 finished with value: 0.589969106188081 and parameters: {'n_estimators': 300, 'max_depth': 8, 'learning_rate': 0.09127815799510323, 'subsample': 0.9661451709558936, 'colsample_bytree': 0.5108250728154665, 'reg_alpha': 0.00021259412827992385, 'reg_lambda': 1.3327797860340052e-08}. Best is trial 0 with value: 0.6282907557601989.
[I 2026-06-13 18:27:31,409] Trial 11 finished with value: 0.5946596729042863 and parameters: {'n_estimators': 300, 'max_depth': 9, 'learning_rate': 0.09927334436030408, 'subsample': 0.9968676185612808, 'colsample_bytree': 0.5040206103892897, 'reg_alpha': 4.997544746782185e-05, 'reg_lambda': 1.6936502473309486e-08}. Best is trial 0 with value: 0.6282907557601989.
[I 2026-06-13 18:32:36,010] Trial 12 finished with value: 0.5939603432474501 and parameters: {'n_estimators': 250, 'max_depth': 10, 'learning_rate': 0.09848920654614607, 'subsample': 0.886733279737485, 'colsample_bytree': 0.5920552685676397, 'reg_alpha': 1.261111925404787e-05, 'reg_lambda': 2.5706617512797072e-08}. Best is trial 0 with value: 0.6282907557601989.
[I 2026-06-13 18:38:47,538] Trial 13 finished with value: 0.6083081927485487 and parameters: {'n_estimators': 300, 'max_depth': 10, 'learning_rate': 0.06517141496914801, 'subsample': 0.9934311794363789, 'colsample_bytree': 0.5962032728335486, 'reg_alpha': 1.4391960396077776e-08, 'reg_lambda': 6.563146419748597e-07}. Best is trial 0 with value: 0.6282907557601989.
[I 2026-06-13 18:50:03,473] Trial 14 finished with value: 0.6109323831150741 and parameters: {'n_estimators': 350, 'max_depth': 11, 'learning_rate': 0.05659267623300038, 'subsample': 0.9002286521620839, 'colsample_bytree': 0.6123366282341044, 'reg_alpha': 1.81408947854658e-08, 'reg_lambda': 7.461544217853947e-07}. Best is trial 0 with value: 0.6282907557601989.
[I 2026-06-13 19:04:26,766] Trial 15 finished with value: 0.6114690711072708 and parameters: {'n_estimators': 400, 'max_depth': 11, 'learning_rate': 0.02483074507475696, 'subsample': 0.8937443212393354, 'colsample_bytree': 0.6133882064972973, 'reg_alpha': 1.8096004243182242e-07, 'reg_lambda': 1.1426317436115783e-06}. Best is trial 0 with value: 0.6282907557601989.
[I 2026-06-13 19:24:40,486] Trial 16 finished with value: 0.5682599406561131 and parameters: {'n_estimators': 500, 'max_depth': 11, 'learning_rate': 0.02199163418016887, 'subsample': 0.7764615120626048, 'colsample_bytree': 0.7897830247330323, 'reg_alpha': 2.579012082582599e-07, 'reg_lambda': 9.813448460510674e-06}. Best is trial 0 with value: 0.6282907557601989.
[I 2026-06-13 19:48:17,586] Trial 17 finished with value: 0.5749582002907936 and parameters: {'n_estimators': 400, 'max_depth': 12, 'learning_rate': 0.03708941274544508, 'subsample': 0.8982509529611884, 'colsample_bytree': 0.7909922530112693, 'reg_alpha': 5.326479272899543e-06, 'reg_lambda': 1.4138414487999646e-07}. Best is trial 0 with value: 0.6282907557601989.
[I 2026-06-13 19:49:19,570] Trial 18 finished with value: 0.5716621058367277 and parameters: {'n_estimators': 200, 'max_depth': 7, 'learning_rate': 0.018840705023244458, 'subsample': 0.7008352541801406, 'colsample_bytree': 0.5720348056712623, 'reg_alpha': 0.0033965476535770573, 'reg_lambda': 7.364144103857295e-06}. Best is trial 0 with value: 0.6282907557601989.
[I 2026-06-13 20:08:38,457] Trial 19 finished with value: 0.5999418410511361 and parameters: {'n_estimators': 500, 'max_depth': 11, 'learning_rate': 0.008543494210570771, 'subsample': 0.8227010571423828, 'colsample_bytree': 0.6473393157679889, 'reg_alpha': 6.161479263106666e-07, 'reg_lambda': 3.978328824572224e-06}. Best is trial 0 with value: 0.6282907557601989.
[I 2026-06-13 20:18:21,347] Trial 20 finished with value: 0.569492554640566 and parameters: {'n_estimators': 400, 'max_depth': 10, 'learning_rate': 0.03041932888208506, 'subsample': 0.6584649011049788, 'colsample_bytree': 0.7752847229001598, 'reg_alpha': 1.994496336579636e-05, 'reg_lambda': 1.0853733791821866e-07}. Best is trial 0 with value: 0.6282907557601989.
[I 2026-06-13 20:29:12,565] Trial 21 finished with value: 0.5845627954780048 and parameters: {'n_estimators': 350, 'max_depth': 11, 'learning_rate': 0.06504950305625443, 'subsample': 0.9088274487291482, 'colsample_bytree': 0.6367009952175001, 'reg_alpha': 1.2357146869387485e-08, 'reg_lambda': 1.120645140615645e-06}. Best is trial 0 with value: 0.6282907557601989.
[I 2026-06-13 20:39:32,028] Trial 22 finished with value: 0.6203434500526321 and parameters: {'n_estimators': 350, 'max_depth': 11, 'learning_rate': 0.05687532697591308, 'subsample': 0.9165164059888778, 'colsample_bytree': 0.5519682063869115, 'reg_alpha': 8.678337548175773e-08, 'reg_lambda': 1.0933988491700495e-07}. Best is trial 0 with value: 0.6282907557601989.
[I 2026-06-13 20:44:33,205] Trial 23 finished with value: 0.6020002429418975 and parameters: {'n_estimators': 400, 'max_depth': 9, 'learning_rate': 0.04420972424606063, 'subsample': 0.941541380027044, 'colsample_bytree': 0.5613888329698153, 'reg_alpha': 1.2887228099372323e-07, 'reg_lambda': 9.037491440148824e-08}. Best is trial 0 with value: 0.6282907557601989.
[I 2026-06-13 20:57:09,883] Trial 24 finished with value: 0.6245281465822987 and parameters: {'n_estimators': 250, 'max_depth': 12, 'learning_rate': 0.035190472586092515, 'subsample': 0.860979440711146, 'colsample_bytree': 0.5638319195627824, 'reg_alpha': 8.100851507556292e-08, 'reg_lambda': 1.0638641869496807e-07}. Best is trial 0 with value: 0.6282907557601989.
[I 2026-06-13 21:07:18,940] Trial 25 finished with value: 0.6144980670074889 and parameters: {'n_estimators': 250, 'max_depth': 12, 'learning_rate': 0.06951685161573908, 'subsample': 0.7903973219380191, 'colsample_bytree': 0.541656992136782, 'reg_alpha': 1.2071710343930381e-06, 'reg_lambda': 5.480406190827484e-08}. Best is trial 0 with value: 0.6282907557601989.
[I 2026-06-13 21:17:28,913] Trial 26 finished with value: 0.6302542475689403 and parameters: {'n_estimators': 200, 'max_depth': 12, 'learning_rate': 0.030590627669285834, 'subsample': 0.858996979312172, 'colsample_bytree': 0.5536926461258819, 'reg_alpha': 7.864845976370929e-08, 'reg_lambda': 2.0641878632329591e-07}. Best is trial 26 with value: 0.6302542475689403.
[I 2026-06-13 21:29:07,287] Trial 27 finished with value: 0.5966477492197484 and parameters: {'n_estimators': 200, 'max_depth': 12, 'learning_rate': 0.03444518828073947, 'subsample': 0.8582950153222332, 'colsample_bytree': 0.6736701896523487, 'reg_alpha': 4.139272544817554e-08, 'reg_lambda': 2.3011666279391286e-05}. Best is trial 26 with value: 0.6302542475689403.
[I 2026-06-13 21:33:41,907] Trial 28 finished with value: 0.6094433382974025 and parameters: {'n_estimators': 200, 'max_depth': 10, 'learning_rate': 0.017950135487907547, 'subsample': 0.7294425184312362, 'colsample_bytree': 0.5787301156552556, 'reg_alpha': 2.235584616686579e-06, 'reg_lambda': 2.918221488816024e-07}. Best is trial 26 with value: 0.6302542475689403.
[I 2026-06-13 21:37:11,653] Trial 29 finished with value: 0.6096246080066127 and parameters: {'n_estimators': 250, 'max_depth': 9, 'learning_rate': 0.04473207987423379, 'subsample': 0.8631612936273038, 'colsample_bytree': 0.5273588040069276, 'reg_alpha': 6.4599471023250054e-06, 'reg_lambda': 2.5894564150350493e-06}. Best is trial 26 with value: 0.6302542475689403.

Best params: {'n_estimators': 200, 'max_depth': 12, 'learning_rate': 0.030590627669285834, 'subsample': 0.858996979312172, 'colsample_bytree': 0.5536926461258819, 'reg_alpha': 7.864845976370929e-08, 'reg_lambda': 2.0641878632329591e-07}

[I 2026-06-13 21:47:45,132] A new study created in memory with name: no-name-3cfd0a7f-7252-41b2-880a-8a91aef17289

Test performance: WAPE=0.0869, R2=0.6303, Bias=-0.4149

============================================================
Training XGBoost + LLM embeddings for: COPD

[I 2026-06-13 21:59:43,759] Trial 0 finished with value: 0.7324954052462568 and parameters: {'n_estimators': 250, 'max_depth': 12, 'learning_rate': 0.044803926826840625, 'subsample': 0.7993292420985183, 'colsample_bytree': 0.5780093202212182, 'reg_alpha': 1.7699302940633311e-07, 'reg_lambda': 2.9152036385288193e-08}. Best is trial 0 with value: 0.7324954052462568.
[I 2026-06-13 22:07:24,310] Trial 1 finished with value: 0.6494904211540876 and parameters: {'n_estimators': 450, 'max_depth': 9, 'learning_rate': 0.04170553216181044, 'subsample': 0.5102922471479012, 'colsample_bytree': 0.9849549260809971, 'reg_alpha': 0.04566054873446119, 'reg_lambda': 4.997040685255803e-07}. Best is trial 0 with value: 0.7324954052462568.
[I 2026-06-13 22:07:41,425] Trial 2 finished with value: 0.5898678696566171 and parameters: {'n_estimators': 150, 'max_depth': 4, 'learning_rate': 0.012439367209907218, 'subsample': 0.762378215816119, 'colsample_bytree': 0.7159725093210578, 'reg_alpha': 2.1371407316372935e-06, 'reg_lambda': 0.000784915956255507}. Best is trial 0 with value: 0.7324954052462568.
[I 2026-06-13 22:08:06,771] Trial 3 finished with value: 0.5845031552749884 and parameters: {'n_estimators': 150, 'max_depth': 5, 'learning_rate': 0.014983654548550792, 'subsample': 0.728034992108518, 'colsample_bytree': 0.8925879806965068, 'reg_alpha': 3.9572205641009174e-07, 'reg_lambda': 0.00012997969313168238}. Best is trial 0 with value: 0.7324954052462568.
[I 2026-06-13 22:08:29,216] Trial 4 finished with value: 0.6340919924967896 and parameters: {'n_estimators': 350, 'max_depth': 3, 'learning_rate': 0.030860579740535368, 'subsample': 0.5852620618436457, 'colsample_bytree': 0.5325257964926398, 'reg_alpha': 0.39001768308022033, 'reg_lambda': 0.530953226900921}. Best is trial 0 with value: 0.7324954052462568.
[I 2026-06-13 22:10:19,982] Trial 5 finished with value: 0.6286328853933931 and parameters: {'n_estimators': 450, 'max_depth': 6, 'learning_rate': 0.006699530280754897, 'subsample': 0.8421165132560784, 'colsample_bytree': 0.7200762468698007, 'reg_alpha': 9.469038421774442e-08, 'reg_lambda': 9.149877525022172e-05}. Best is trial 0 with value: 0.7324954052462568.
[I 2026-06-13 22:16:39,435] Trial 6 finished with value: 0.621556818828736 and parameters: {'n_estimators': 100, 'max_depth': 12, 'learning_rate': 0.010855517271883068, 'subsample': 0.831261142176991, 'colsample_bytree': 0.6558555380447055, 'reg_alpha': 0.00014472520367197597, 'reg_lambda': 0.00023641892308789696}. Best is trial 0 with value: 0.7324954052462568.
[I 2026-06-13 22:27:07,375] Trial 7 finished with value: 0.6003820817300285 and parameters: {'n_estimators': 150, 'max_depth': 12, 'learning_rate': 0.05098483969585744, 'subsample': 0.9697494707820946, 'colsample_bytree': 0.9474136752138245, 'reg_alpha': 0.0006070155694141794, 'reg_lambda': 0.23713402899336497}. Best is trial 0 with value: 0.7324954052462568.
[I 2026-06-13 22:27:18,795] Trial 8 finished with value: 0.4278344527263742 and parameters: {'n_estimators': 100, 'max_depth': 4, 'learning_rate': 0.005725482134163321, 'subsample': 0.6626651653816322, 'colsample_bytree': 0.6943386448447411, 'reg_alpha': 1.481809088646707e-06, 'reg_lambda': 0.04264813784432918}. Best is trial 0 with value: 0.7324954052462568.
[I 2026-06-13 22:27:58,311] Trial 9 finished with value: 0.6118226742202028 and parameters: {'n_estimators': 250, 'max_depth': 5, 'learning_rate': 0.025411709798607296, 'subsample': 0.5704621124873813, 'colsample_bytree': 0.9010984903770198, 'reg_alpha': 3.9482545946332394e-08, 'reg_lambda': 0.7854083114461319}. Best is trial 0 with value: 0.7324954052462568.
[I 2026-06-13 22:30:07,726] Trial 10 finished with value: 0.7295198130611354 and parameters: {'n_estimators': 300, 'max_depth': 8, 'learning_rate': 0.09127815799510323, 'subsample': 0.9661451709558936, 'colsample_bytree': 0.5108250728154665, 'reg_alpha': 0.00021259412827992385, 'reg_lambda': 1.3327797860340052e-08}. Best is trial 0 with value: 0.7324954052462568.
[I 2026-06-13 22:33:32,243] Trial 11 finished with value: 0.7235502525004822 and parameters: {'n_estimators': 300, 'max_depth': 9, 'learning_rate': 0.09927334436030408, 'subsample': 0.9968676185612808, 'colsample_bytree': 0.5040206103892897, 'reg_alpha': 4.997544746782185e-05, 'reg_lambda': 1.6936502473309486e-08}. Best is trial 0 with value: 0.7324954052462568.
[I 2026-06-13 22:36:39,345] Trial 12 finished with value: 0.7151910569140423 and parameters: {'n_estimators': 250, 'max_depth': 9, 'learning_rate': 0.09844180615630226, 'subsample': 0.8922867929837619, 'colsample_bytree': 0.5920552685676397, 'reg_alpha': 0.006468055996739627, 'reg_lambda': 2.5706617512797072e-08}. Best is trial 0 with value: 0.7324954052462568.
[I 2026-06-13 22:38:17,924] Trial 13 finished with value: 0.7142300199120755 and parameters: {'n_estimators': 300, 'max_depth': 7, 'learning_rate': 0.06497317979705144, 'subsample': 0.9239124345965728, 'colsample_bytree': 0.5962032728335486, 'reg_alpha': 1.703873561972944e-05, 'reg_lambda': 6.563146419748597e-07}. Best is trial 0 with value: 0.7324954052462568.
[I 2026-06-13 22:48:11,594] Trial 14 finished with value: 0.726089506435754 and parameters: {'n_estimators': 350, 'max_depth': 11, 'learning_rate': 0.06648299543108013, 'subsample': 0.7883748688419223, 'colsample_bytree': 0.5859947096170142, 'reg_alpha': 0.0020288569587832857, 'reg_lambda': 3.897742686746601e-07}. Best is trial 0 with value: 0.7324954052462568.
[I 2026-06-13 22:52:58,550] Trial 15 finished with value: 0.7358252879452671 and parameters: {'n_estimators': 250, 'max_depth': 10, 'learning_rate': 0.025680776870599838, 'subsample': 0.7016792848320459, 'colsample_bytree': 0.5008787890646734, 'reg_alpha': 8.690226536331963e-06, 'reg_lambda': 3.6440953963738784e-06}. Best is trial 15 with value: 0.7358252879452671.
[I 2026-06-13 23:03:35,393] Trial 16 finished with value: 0.6638114717403136 and parameters: {'n_estimators': 250, 'max_depth': 11, 'learning_rate': 0.02199163418016887, 'subsample': 0.6924745509172271, 'colsample_bytree': 0.7947992509228796, 'reg_alpha': 1.0580292454421503e-08, 'reg_lambda': 9.813448460510674e-06}. Best is trial 15 with value: 0.7358252879452671.
[I 2026-06-13 23:07:50,965] Trial 17 finished with value: 0.7074897918074434 and parameters: {'n_estimators': 200, 'max_depth': 10, 'learning_rate': 0.03812142477043449, 'subsample': 0.6430104032327739, 'colsample_bytree': 0.6212239558377118, 'reg_alpha': 6.442621877903942e-06, 'reg_lambda': 4.023465173414626e-06}. Best is trial 15 with value: 0.7358252879452671.
[I 2026-06-13 23:20:57,003] Trial 18 finished with value: 0.729725763764146 and parameters: {'n_estimators': 400, 'max_depth': 11, 'learning_rate': 0.01939587347734006, 'subsample': 0.8005173854663322, 'colsample_bytree': 0.5526908165068332, 'reg_alpha': 2.5357299033105315e-07, 'reg_lambda': 7.746697091497292e-08}. Best is trial 15 with value: 0.7358252879452671.

In [ ]:
for target in ['prcDiabetes', 'prcStroke']:
    print(f"\n{'='*60}")
    print(f"Training XGBoost + LLM embeddings for: {disease_names[target]}")

    X_train = train_df_emb[features_with_emb]
    y_train = train_df_emb[target]
    X_test = test_df_emb[features_with_emb]
    y_test = test_df_emb[target]

    study = optuna.create_study(direction='maximize', sampler=optuna.samplers.TPESampler(seed=42))
    study.optimize(lambda trial: objective(trial, X_train, y_train, X_test, y_test), n_trials=30, show_progress_bar=False)

    best_params = study.best_params
    print(f"Best params: {best_params}")

    final_model = xgb.XGBRegressor(objective='reg:squarederror', random_state=42, **best_params)
    final_model.fit(X_train, y_train)

    y_pred = final_model.predict(X_test)
    wape = weighted_absolute_percentage_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)
    bias = mean_bias(y_test, y_pred)

    print(f"Test performance: WAPE={wape:.4f}, R2={r2:.4f}, Bias={bias:.4f}")

    emb_results.append({
        'Disease': disease_names[target],
        'WAPE': wape,
        'R2': r2,
        'Bias': bias,
        'Model_Type': 'XGBoost + LLM Emb'
    })

In [1]:
emb_df = pd.DataFrame(emb_results)
print("\nXGBoost + LLM Embeddings Summary:")
emb_df

NameError: name 'pd' is not defined